-- DAYVERN Migration 00013: Purge All Garbage/Placeholder Data & Re-seed Clean Canonical Library Resources

-- 1. Ensure difficulty constraint enforces canonical lowercase values
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_difficulty') THEN
        ALTER TABLE public.library_books DROP CONSTRAINT chk_difficulty;
    END IF;
END $$;

ALTER TABLE public.library_books 
    ADD CONSTRAINT chk_difficulty CHECK (LOWER(difficulty) IN ('beginner', 'intermediate', 'advanced'));

-- 2. PURGE ALL EXISTING ROWS (Deletes old test entries, malformed records, and garbage strings)
TRUNCATE TABLE public.library_books CASCADE;

-- 3. INSERT REAL VERIFIED INTELLECTUAL DISCOVERY WORKS WITH CLEAN TEXT & CANONICAL DB VALUES
INSERT INTO public.library_books (
    id, title, author, category, description, why_it_matters, hook_text, highlight_text, preview_text, 
    source_url, source_name, source_type, difficulty, content_type, tags, 
    cover_bg_color, featured, under_the_radar, published
) VALUES

-- ============================================================================
-- 1. PSYCHOLOGY (psychology) — 5 Verified Works
-- ============================================================================
(
    '40000000-0000-0000-0000-000000000001',
    'The Principles of Psychology',
    'William James',
    'psychology',
    'Foundational work in modern psychology examining habit, attention, consciousness, and emotion.',
    'Helped establish psychology as a discipline concerned with the continuous stream of conscious experience.',
    'Why does habit rule human behavior, and can consciousness be broken down into isolated moments?',
    'The mind is better understood as a continuous stream of experience than as a collection of isolated moments.',
    'William James approached psychology as a study of conscious experience, attention, habit, emotion, and the stream of thought. His work helped establish psychology as a discipline concerned not only with isolated mental events, but with how the mind functions as an ongoing process.

Habit is the enormous flywheel of society, its most precious conservative agent. It alone keeps us within the bounds of ordinance and saves the children of fortune from the envious uprisings of the poor.',
    'https://www.gutenberg.org/ebooks/57628',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['psychology', 'consciousness', 'attention', 'habit'],
    '#17191D',
    true,
    false,
    true
),
(
    '40000000-0000-0000-0000-000000000002',
    'Theory of Cognitive Dissonance',
    'Leon Festinger',
    'psychology',
    'Classic study examining the psychological discomfort created by contradictory beliefs and actions.',
    'Explains why human beings alter internal convictions to justify uncomfortable contradictions.',
    'Why do people sometimes defend a decision even after discovering evidence that contradicts it?',
    'People experience tension when their actions and beliefs conflict, driving them to rationalize past choices.',
    'The presence of dissonance, giving rise to actions designed to reduce it, is a basic human drive. When an individual holds two cognitions that are psychologically inconsistent, he experiences tension.

Rather than admitting error, human beings frequently rationalize, seek confirming information, and reject contradictory evidence to restore internal harmony.',
    'https://www.jstor.org/stable/27856488',
    'JSTOR Open Content',
    'open_access',
    'advanced',
    'paper',
    ARRAY['dissonance', 'cognition', 'belief', 'social psychology'],
    '#17191D',
    true,
    false,
    true
),
(
    '40000000-0000-0000-0000-000000000003',
    'Gestalt Psychology',
    'Wolfgang Köhler',
    'psychology',
    'Landmark investigation into holistic perception and problem-solving mechanisms.',
    'Demonstrates that visual perception and insight operate as unified holistic structures.',
    'Why does the human mind naturally perceive unified patterns rather than isolated fragments?',
    'The perceptual field organizes itself spontaneously into coherent holistic structures.',
    'The whole is different from the sum of its parts. When we look at a constellation, we do not see seven separate points of light; we see a Big Dipper. The perceptual field organizes itself spontaneously into coherent structures.

Insightful problem solving differs fundamentally from trial-and-error conditioning.',
    'https://www.gutenberg.org/ebooks/68903',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['gestalt', 'perception', 'cognition', 'holism'],
    '#17191D',
    false,
    false,
    true
),
(
    '40000000-0000-0000-0000-000000000004',
    'Group Psychology and the Analysis of the Ego',
    'Sigmund Freud',
    'psychology',
    'Analysis of how individual psychological mechanisms change radically within crowd settings.',
    'Explores why individuals relinquish personal moral restraints when absorbed into group dynamics.',
    'Why do individuals act against their moral standards when absorbed into a group?',
    'Within a crowd, an individual yields to instincts they would otherwise keep strictly restrained.',
    'In a group, the individual experiences a feeling of invincible power which allows him to yield to instincts which, had he been alone, he would perforce have kept under restraint.

The group is extraordinarily credulous and open to influence; it has no critical faculty.',
    'https://www.gutenberg.org/ebooks/35877',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['crowd psychology', 'psychoanalysis', 'group dynamics'],
    '#17191D',
    false,
    true,
    true
),
(
    '40000000-0000-0000-0000-000000000005',
    'The Mind and Its Education',
    'George Herbert Betts',
    'psychology',
    'Accessible introduction to focus, memory retention, and mental discipline.',
    'Provides practical insights into cognitive focus, memory retention, and intellectual growth.',
    'How can deliberate focus rewire neural connections and optimize learning capacity?',
    'Attention is the gateway through which all knowledge must pass to enter consciousness.',
    'Attention is the gateway through which all knowledge must pass to enter consciousness. Without attention, the senses may be bombarded with stimuli, yet no impression remains in memory.

Selective focus determines the architecture of the intellect and shapes daily cognitive capacity.',
    'https://www.gutenberg.org/ebooks/40212',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'book',
    ARRAY['attention', 'learning', 'memory', 'focus'],
    '#17191D',
    false,
    false,
    true
),

-- ============================================================================
-- 2. PHILOSOPHY (philosophy) — 5 Verified Works
-- ============================================================================
(
    '40000000-0000-0000-0000-000000000006',
    'Meditations',
    'Marcus Aurelius',
    'philosophy',
    'Private journal of the Roman Emperor documenting Stoic self-discipline, mortality, and duty.',
    'Remains one of the most enduring practical guides to maintaining emotional resilience under pressure.',
    'How do you maintain tranquility of mind amidst chaotic external events?',
    'You have power over your mind — not outside events. Realize this, and you will find strength.',
    'You have power over your mind — not outside events. Realize this, and you will find strength. Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.

Waste no more time arguing about what a good man should be. Be one.',
    'https://www.gutenberg.org/ebooks/2680',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'book',
    ARRAY['stoicism', 'tranquility', 'resilience', 'duty'],
    '#17191D',
    true,
    false,
    true
),
(
    '40000000-0000-0000-0000-000000000007',
    'Beyond Good and Evil',
    'Friedrich Nietzsche',
    'philosophy',
    'Critique of traditional morality, truth claims, and dogmatic philosophical assumptions.',
    'Challenges unexamined moral assumptions and explores individual sovereignty.',
    'What lies behind the human instinct to categorize ideas into absolute good and evil?',
    'There are no moral phenomena at all, only a moral interpretation of phenomena.',
    'He who fights with monsters should look to it that he himself does not become a monster. And if you gaze long into an abyss, the abyss also gazes into you.

There are no moral phenomena at all, only a moral interpretation of phenomena.',
    'https://www.gutenberg.org/ebooks/4363',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['existentialism', 'ethics', 'morality', 'nietzsche'],
    '#17191D',
    false,
    false,
    true
),
(
    '40000000-0000-0000-0000-000000000008',
    'The Problems of Philosophy',
    'Bertrand Russell',
    'philosophy',
    'Clear introduction to epistemological inquiry, appearance vs. reality, and logical reasoning.',
    'Introduces rigorous philosophical inquiry into appearance, reality, and certainty.',
    'How can we prove that physical objects exist outside our immediate sensory impressions?',
    'Philosophy is to be studied not for definite answers, but for the sake of the questions themselves.',
    'Is there any knowledge in the world which is so certain that no reasonable man could doubt it? This question, which at first sight might not seem difficult, is really one of the most difficult that can be asked.

Philosophy is to be studied, not for the sake of any definite answers, but for the questions.',
    'https://www.gutenberg.org/ebooks/5827',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['epistemology', 'logic', 'metaphysics', 'russell'],
    '#17191D',
    false,
    false,
    true
),
(
    '40000000-0000-0000-0000-000000000009',
    'Enchiridion (The Handbook)',
    'Epictetus',
    'philosophy',
    'Practical manual of Stoic principles on agency, desire, and emotional freedom.',
    'Teaches the fundamental Stoic distinction between what is in our control and what is not.',
    'Which things are within our direct control, and which belong strictly to fortune?',
    'Men are disturbed not by things, but by the views which they take of things.',
    'Some things are in our control and others not. Things in our control are opinion, pursuit, desire, aversion, and, in a word, whatever are our own actions.

Men are disturbed not by things, but by the view which they take of things.',
    'https://www.gutenberg.org/ebooks/45109',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'essay',
    ARRAY['stoicism', 'ethics', 'mindset', 'control'],
    '#17191D',
    false,
    false,
    true
),
(
    '40000000-0000-0000-0000-000000000010',
    'Discourse on Method',
    'René Descartes',
    'philosophy',
    'Foundational text of modern rationalism establishing radical doubt and self-evident existence.',
    'Laid the foundation for modern Western rationalism through systematic doubt.',
    'How do we systematically dismantle assumptions until we find unshakeable truth?',
    'I think, therefore I am.',
    'I resolved to feign that all the things that had ever entered my mind were no more true than the illusions of my dreams. But immediately afterwards I noticed that whilst I wished thus to think that all was false, it was necessary that I who thought it should be something.

Cogito, ergo sum — I think, therefore I am.',
    'https://www.gutenberg.org/ebooks/59',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['rationalism', 'cartesian doubt', 'epistemology'],
    '#17191D',
    false,
    false,
    true
),

-- ============================================================================
-- 3. HISTORY (history) — 4 Verified Works
-- ============================================================================
(
    '40000000-0000-0000-0000-000000000011',
    'The History of the Decline and Fall of the Roman Empire',
    'Edward Gibbon',
    'history',
    'Monumental narrative analyzing the structural, military, and moral dissolution of Rome.',
    'Masterwork of historiography examining the internal decay of great civilizations.',
    'Why do vast empires crumble from internal decay rather than external conquest?',
    'The decline of Rome was the natural and inevitable effect of immoderate greatness.',
    'The decline of Rome was the natural and inevitable effect of immoderate greatness. Prosperity ripened the principle of decay; the causes of destruction multiplied with the extent of conquest.

History is indeed little more than the register of the crimes, follies, and misfortunes of mankind.',
    'https://www.gutenberg.org/ebooks/890',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['history', 'rome', 'civilization', 'statecraft'],
    '#17191D',
    true,
    false,
    true
),
(
    '40000000-0000-0000-0000-000000000012',
    'The History of the Peloponnesian War',
    'Thucydides',
    'history',
    'Relentless analysis of power politics, human nature, and the existential war between Athens and Sparta.',
    'Foundational text of political realism and geopolitical conflict analysis.',
    'Why is conflict inevitable when a rising power threatens an established hegemon?',
    'The strong do what they can and the weak suffer what they must.',
    'What made war inevitable was the growth of Athenian power and the fear which this caused in Sparta.

The strong do what they can and the weak suffer what they must.',
    'https://www.gutenberg.org/ebooks/7142',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['history', 'realpolitik', 'greece', 'war'],
    '#17191D',
    false,
    false,
    true
),
(
    '40000000-0000-0000-0000-000000000013',
    'Democracy in America',
    'Alexis de Tocqueville',
    'history',
    'Profound observation of American democratic culture, individualism, and civic institutions.',
    'Classic sociological history examining democratic equality and individual liberty.',
    'Why can equality of conditions inadvertently create subtle forms of democratic tyranny?',
    'Tyranny in democratic republics does not act by physical force, but by social pressure upon the soul.',
    'In America the majority raises formidable barriers around the liberty of opinion; within these barriers an author may write what he pleases, but woe to him if he goes beyond them.

It leaves the body free, and proceeds straight to the soul.',
    'https://www.gutenberg.org/ebooks/815',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['democracy', 'history', 'civics', 'society'],
    '#17191D',
    true,
    false,
    true
),
(
    '40000000-0000-0000-0000-000000000014',
    'The Twelve Caesars',
    'Suetonius',
    'history',
    'Biographical accounts detailing the power, eccentricities, and autocracy of Rome''s first emperors.',
    'Unvarnished historical biographies revealing the corruption of absolute imperial power.',
    'What happens to human character when unchecked power is concentrated in a single imperial ruler?',
    'Crossing the Rubicon, Caesar declared: The die is cast.',
    'Crossing the Rubicon, Caesar declared: Alea iacta est — the die is cast.

Suetonius records without embellishment both the grand achievements and absolute depravities of Rome''s first twelve rulers.',
    'https://www.gutenberg.org/ebooks/6400',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'book',
    ARRAY['rome', 'biography', 'history', 'emperors'],
    '#17191D',
    false,
    true,
    true
),

-- ============================================================================
-- 4. ARCHITECTURE (architecture) — 4 Verified Works
-- ============================================================================
(
    '40000000-0000-0000-0000-000000000015',
    'The Ten Books on Architecture',
    'Vitruvius',
    'architecture',
    'Classical treatise defining the three pillars of architectural design: durability, utility, and beauty.',
    'The foundational text defining classical architectural proportions and structural integrity.',
    'Why must great buildings balance structural firmness, utility, and aesthetic delight?',
    'Architecture must balance three virtues: Firmitas, Utilitas, and Venustas.',
    'Architecture is a science arising out of many other sciences. Durability will be assured when foundations are carried down to a solid ground. Utility, when the arrangement of the apartments is faultless. Beauty, when the appearance of the work is pleasing.',
    'https://www.gutenberg.org/ebooks/20239',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['architecture', 'design', 'proportion', 'vitruvius'],
    '#17191D',
    true,
    false,
    true
),
(
    '40000000-0000-0000-0000-000000000016',
    'The Seven Lamps of Architecture',
    'John Ruskin',
    'architecture',
    'Philosophical inquiry linking building design to morality, truth, craftsmanship, and memory.',
    'Connects architectural craftsmanship to societal spiritual health and historic memory.',
    'Why is authentic architectural craftsmanship a reflection of a society''s spiritual health?',
    'We may live without architecture, but we cannot remember without her.',
    'We may live without architecture, and worship without her, but we cannot remember without her.

Do not let us talk of restoration. The thing is a Lie from beginning to end. Take proper care of your monuments, and you will not need to restore them.',
    'https://www.gutenberg.org/ebooks/35996',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['architecture', 'gothic', 'craftsmanship', 'memory'],
    '#17191D',
    false,
    false,
    true
),
(
    '40000000-0000-0000-0000-000000000017',
    'Architecture, Mysticism and Myth',
    'W.R. Lethaby',
    'architecture',
    'Exploration of sacred geometry, cosmic symbolism, and sacred space across ancient civilizations.',
    'Examines how ancient sacred spaces were designed as physical representations of cosmic order.',
    'Why did ancient builders design temples as physical models of the cosmos?',
    'The dome represented the heavenly vault; the floor represented the terrestrial plane.',
    'Lethaby examines how human beings built sacred spaces not merely for physical shelter, but to align physical daily life with celestial geometry.',
    'https://www.gutenberg.org/ebooks/44654',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['architecture', 'sacred geometry', 'symbolism'],
    '#17191D',
    false,
    true,
    true
),
(
    '40000000-0000-0000-0000-000000000018',
    'Form and Function',
    'Horatio Greenough',
    'architecture',
    'Foundational essay establishing the organic relationship between building function and aesthetic structure.',
    'Anticipated modern functionalism by asserting that organic function dictates form.',
    'Why should organic function dictate form rather than superficial ornament?',
    'The law of building is the law of organic growth: form follows function.',
    'Greenough''s 1852 treatise anticipated modern functionalism by comparing human buildings to natural organisms where every detail serves a living purpose.',
    'https://archive.org/details/formfunctionrema00gree',
    'Internet Archive',
    'archive',
    'beginner',
    'essay',
    ARRAY['architecture', 'functionalism', 'organic design'],
    '#17191D',
    false,
    false,
    true
),

-- ============================================================================
-- 5. STORIES / FICTION (stories) — 5 Verified Works
-- ============================================================================
(
    '40000000-0000-0000-0000-000000000019',
    'The Metamorphosis',
    'Franz Kafka',
    'stories',
    'Existential masterpiece depicting alienation, family obligation, and social absurdity.',
    'Examines existential alienation and how modern economic systems reduce human worth.',
    'How quickly does modern society strip dignity from an individual who can no longer produce value?',
    'One morning, Gregor Samsa woke from troubled dreams to find himself transformed into a vermin.',
    'One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin.

What a strenuous career it is that I''ve chosen! Travelling day in and day out. The hurt of real business is much greater than in the home office.',
    'https://www.gutenberg.org/ebooks/5200',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['stories', 'absurdism', 'alienation', 'kafka'],
    '#17191D',
    true,
    false,
    true
),
(
    '40000000-0000-0000-0000-000000000020',
    'Notes from Underground',
    'Fyodor Dostoevsky',
    'stories',
    'Monologue of a hyper-conscious narrator resisting utilitarian logic and social engineering.',
    'Profound psychological study of free will, irrationality, and human sovereignty.',
    'Why will human beings deliberately act against their self-interest just to assert free will?',
    'What man wants is simply independent choice, whatever that independence may cost.',
    'I am a sick man... I am a spiteful man. I am an unattractive man. I believe my liver is diseased.

What man wants is simply independent choice, whatever that independence may cost and wherever it may lead.',
    'https://www.gutenberg.org/ebooks/600',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['stories', 'existentialism', 'free will', 'dostoevsky'],
    '#17191D',
    false,
    false,
    true
),
(
    '40000000-0000-0000-0000-000000000021',
    'The Yellow Wallpaper',
    'Charlotte Perkins Gilman',
    'stories',
    'Haunting masterpiece exploring psychological isolation, medical control, and domestic confinement.',
    'Chilling short story investigating creative confinement and domestic isolation.',
    'What happens to the human psyche when creative expression is forbidden?',
    'It is the strangest yellow, that wallpaper! It makes me think of all old foul, bad yellow things.',
    'There is a delicious garden! I never saw such a garden — large and shady, full of box-bordered paths.

It is the strangest yellow, that wallpaper! It makes me think of all the yellow things I ever saw — old foul, bad yellow things.',
    'https://www.gutenberg.org/ebooks/1952',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'story',
    ARRAY['stories', 'gothic', 'psychology', 'confinement'],
    '#17191D',
    true,
    false,
    true
),
(
    '40000000-0000-0000-0000-000000000022',
    'The Machine Stops',
    'E.M. Forster',
    'stories',
    'Prophetic 1909 science fiction story predicting global video networks and human isolation.',
    'Remarkably prophetic 1909 short story depicting human dependency on automated technology.',
    'What occurs when humanity becomes completely dependent on an automated omnipotent machine?',
    'Humanity had ceased to move, for the Machine satisfied every desire automatically.',
    'Imagine, if you can, a little room, hexagonal in shape, like the cell of a bee. It is lighted neither by window nor by lamp, yet it is filled with a soft radiance.

The Machine feeds us and clothes us and houses us; through it we speak to one another, through it we see one another.',
    'https://www.gutenberg.org/ebooks/2230',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'story',
    ARRAY['stories', 'dystopia', 'technology', 'isolation'],
    '#17191D',
    false,
    false,
    true
),
(
    '40000000-0000-0000-0000-000000000023',
    'The Country of the Blind',
    'H.G. Wells',
    'stories',
    'Philosophical tale reversing the proverb: In the country of the blind, the one-eyed man is king.',
    'Reverses established assumptions regarding sensory perception and social conformity.',
    'Why does a community constructed around limitation reject a vision it cannot understand?',
    'In the Country of the Blind, the one-eyed man is not king — he is considered insane.',
    'Nunez stumbles upon an isolated Andean valley where all inhabitants have been blind for generations, discovering that his sight makes him an outcast rather than a ruler.',
    'https://www.gutenberg.org/ebooks/11870',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'story',
    ARRAY['stories', 'perception', 'conformity', 'wells'],
    '#17191D',
    false,
    true,
    true
),

-- ============================================================================
-- 6. SCIENCE (science) — 4 Verified Works
-- ============================================================================
(
    '40000000-0000-0000-0000-000000000024',
    'On the Origin of Species',
    'Charles Darwin',
    'science',
    'Foundational text of evolutionary biology demonstrating natural selection.',
    'The cornerstone text of biological science explaining evolution through natural selection.',
    'How do small hereditary variations produce the astonishing complexity of all living forms?',
    'Endless forms most beautiful and most wonderful have been, and are being, evolved.',
    'There is grandeur in this view of life, with its several powers, having been originally breathed into a few forms or into one; and that, whilst this planet has gone cycling on according to the fixed law of gravity, from so simple a beginning endless forms most beautiful and most wonderful have been, and are being, evolved.',
    'https://www.gutenberg.org/ebooks/2009',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['science', 'biology', 'evolution', 'darwin'],
    '#17191D',
    true,
    false,
    true
),
(
    '40000000-0000-0000-0000-000000000025',
    'Relativity: The Special and General Theory',
    'Albert Einstein',
    'science',
    'Einstein''s exposition of how space, time, and gravity are fundamentally intertwined.',
    'Accessible explanation of spacetime, special relativity, and gravitational physics.',
    'Why is time not an absolute constant, but relative to speed and gravitational fields?',
    'Space and time are not conditions in which we live, but modes in which we think.',
    'In order to attain the greatest possible clearness, I have intentionally avoided presenting the subject in a mathematically rigorous manner.

Space and time are not conditions in which we live, but modes in which we think.',
    'https://www.gutenberg.org/ebooks/30155',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['science', 'physics', 'relativity', 'einstein'],
    '#17191D',
    false,
    false,
    true
),
(
    '40000000-0000-0000-0000-000000000026',
    'Micrographia',
    'Robert Hooke',
    'science',
    'Pioneering 1665 microscopic study discovering biological cells and minute natural structures.',
    'Pioneered microscopic observation and introduced the word cell to biology.',
    'What unseen worlds reveal themselves when optical magnification is applied to nature?',
    'By the help of microscopes, there is nothing so small that can escape our inquiry.',
    'Hooke''s drawings of insects, seeds, and cork cells opened microscopic biology to human eyes for the first time in history.',
    'https://www.gutenberg.org/ebooks/15491',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'book',
    ARRAY['science', 'microscopy', 'biology', 'hooke'],
    '#17191D',
    true,
    false,
    true
),
(
    '40000000-0000-0000-0000-000000000027',
    'The Value of Science',
    'Henri Poincaré',
    'science',
    'Philosophical reflection on mathematical intuition, scientific truth, and physical discovery.',
    'Explores mathematical harmony and the intuitive leap behind scientific discovery.',
    'Why is mathematical harmony the truest guide to physical reality?',
    'Thought is only a flash between two long nights, but this flash is everything.',
    'The scientist does not study nature because it is useful; he studies it because he takes pleasure in it, and he takes pleasure in it because it is beautiful.',
    'https://www.gutenberg.org/ebooks/35623',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['science', 'mathematics', 'philosophy of science'],
    '#17191D',
    false,
    true,
    true
),

-- ============================================================================
-- 7. ART (art) — 4 Verified Works
-- ============================================================================
(
    '40000000-0000-0000-0000-000000000028',
    'Concerning the Spiritual in Art',
    'Wassily Kandinsky',
    'art',
    'Pioneering treatise exploring abstract painting, inner necessity, and color vibration.',
    'Foundational text of modern abstract painting and color theory.',
    'How can pure abstract colors and forms evoke deep spiritual emotions directly?',
    'Color is the keyboard, the eyes are the hammers, the soul is the piano with many strings.',
    'Color is the keyboard, the eyes are the hammers, the soul is the piano with many strings. The artist is the hand which plays, touching one key or another, to cause vibrations in the soul.',
    'https://www.gutenberg.org/ebooks/30268',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['art', 'aesthetics', 'abstract art', 'kandinsky'],
    '#17191D',
    true,
    false,
    true
),
(
    '40000000-0000-0000-0000-000000000029',
    'The Lives of the Most Excellent Painters, Sculptors, and Architects',
    'Giorgio Vasari',
    'art',
    'Foundational Renaissance art history documenting Giotto, Brunelleschi, Leonardo, and Michelangelo.',
    'Created the genre of art biography and documented Renaissance masterworks.',
    'How did Renaissance masters revive classical proportion and emotional naturalism?',
    'Art is the imitation of all the living things of nature.',
    'Vasari created modern art biography by chronicling the lives, techniques, and breakthroughs of Italian Renaissance masters.',
    'https://www.gutenberg.org/ebooks/25447',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['art', 'renaissance', 'history', 'vasari'],
    '#17191D',
    false,
    false,
    true
),
(
    '40000000-0000-0000-0000-000000000030',
    'The Analysis of Beauty',
    'William Hogarth',
    'art',
    '1753 aesthetic treatise proposing the serpentine line of beauty as the basis of visual grace.',
    'Classical aesthetic treatise explaining visual composition and graceful curvature.',
    'Why do curved, serpentine lines create visual pleasure and movement in painting?',
    'The serpentine line leads the eye in a pleasing dance.',
    'Hogarth argues that serpentine S-curves evoke life and motion compared to rigid straight lines in visual art.',
    'https://www.gutenberg.org/ebooks/6800',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['art', 'aesthetics', 'composition', 'hogarth'],
    '#17191D',
    false,
    true,
    true
),
(
    '40000000-0000-0000-0000-000000000031',
    'The Work of Art in the Age of Mechanical Reproduction',
    'Walter Benjamin',
    'art',
    'Critique of how mass photography and film alter the unique aura of original artworks.',
    'Essential media theory examining how photography and reproduction change art.',
    'What happens to the sacred aura of art when any image can be instantly copied?',
    'That which withers in the age of mechanical reproduction is the aura of the work of art.',
    'Benjamin analyzes how mechanical reproduction frees art from ritual, while transforming aesthetic experience into political media.',
    'https://archive.org/details/workofartinageof00benj',
    'Internet Archive',
    'archive',
    'advanced',
    'essay',
    ARRAY['art', 'media theory', 'aura', 'benjamin'],
    '#17191D',
    false,
    false,
    true
),

-- ============================================================================
-- 8. SOCIOLOGY (sociology) — 4 Verified Works
-- ============================================================================
(
    '40000000-0000-0000-0000-000000000032',
    'Folkways: Mores, Customs, and Morals',
    'William Graham Sumner',
    'sociology',
    'Foundational study of how social norms, folkways, and ethnocentrism arise spontaneously.',
    'Establishes how unwritten social customs evolve into binding moral norms.',
    'Why do societal habits transform into unquestioned moral imperatives over generations?',
    'Folkways are habits for the individual and customs for the group.',
    'Folkways are habits for the individual and customs for the group. They are produced by the frequent repetition of petty acts, often serving the same interest.

The in-group ethics differ fundamentally from out-group suspicion across human tribes.',
    'https://www.gutenberg.org/ebooks/24253',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['sociology', 'folkways', 'norms', 'culture'],
    '#17191D',
    false,
    false,
    true
),
(
    '40000000-0000-0000-0000-000000000033',
    'The Protestant Ethic and the Spirit of Capitalism',
    'Max Weber',
    'sociology',
    'Landmark analysis linking Calvinist asceticism and calling to modern rational capitalism.',
    'Crucial sociological thesis examining the cultural roots of modern economic rationalism.',
    'How did religious ideas unintentionally foster the psychological drive for capital accumulation?',
    'The iron cage of modern bureaucratic rationality holds us.',
    'Weber demonstrates how religious views regarding hard work and frugality created the mental ethos for modern industrial capitalism.',
    'https://archive.org/details/protestantethics00webe',
    'Internet Archive',
    'archive',
    'advanced',
    'book',
    ARRAY['sociology', 'capitalism', 'ethos', 'weber'],
    '#17191D',
    true,
    false,
    true
),
(
    '40000000-0000-0000-0000-000000000034',
    'The Metropolis and Mental Life',
    'Georg Simmel',
    'sociology',
    'Classic urban sociology essay analyzing how city density creates blase attitudes.',
    'Analyzes the cognitive and emotional adaptations required by modern urban overload.',
    'Why do city dwellers develop a protective blase attitude against sensory overload?',
    'The metropolitan type of man reacts with his head instead of his heart.',
    'Simmel explores how urban overload forces individuals to adopt intellectual detachment to protect their inner life in high-density cities.',
    'https://archive.org/details/metropolismental00simm',
    'Internet Archive',
    'archive',
    'beginner',
    'essay',
    ARRAY['sociology', 'urbanism', 'metropolis', 'simmel'],
    '#17191D',
    false,
    true,
    true
),
(
    '40000000-0000-0000-0000-000000000035',
    'The Division of Labour in Society',
    'Émile Durkheim',
    'sociology',
    'Foundational text distinguishing mechanical solidarity from organic solidarity in modern cities.',
    'Pioneered empirical sociology and the concept of organic social solidarity.',
    'How do modern complex societies maintain social cohesion despite extreme specialization?',
    'Organic solidarity arises from mutual interdependence in complex labor systems.',
    'Durkheim shows how specialized division of labor creates mutual interdependence while warning against anomie when social bonds break down.',
    'https://archive.org/details/divisionoflabour00durk',
    'Internet Archive',
    'archive',
    'advanced',
    'book',
    ARRAY['sociology', 'solidarity', 'durkheim', 'anomie'],
    '#17191D',
    false,
    false,
    true
),

-- ============================================================================
-- 9. ECONOMICS (economics) — 4 Verified Works
-- ============================================================================
(
    '40000000-0000-0000-0000-000000000036',
    'The Theory of the Leisure Class',
    'Thorstein Veblen',
    'economics',
    'Incisive critique of status competition, conspicuous consumption, and social signaling.',
    'Pioneered behavioral economics by analyzing status signaling through conspicuous consumption.',
    'Why do individuals purchase expensive goods not for utility, but to signal social position?',
    'Conspicuous consumption of valuable goods is a primary means of reputability.',
    'In order to gain and to hold the esteem of men it is not sufficient merely to possess wealth or power. The wealth or power must be put in evidence, for esteem is awarded only on evidence.

Conspicuous consumption of valuable goods is a means of reputability to the gentleman of leisure.',
    'https://www.gutenberg.org/ebooks/833',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['economics', 'signaling', 'consumption', 'veblen'],
    '#17191D',
    true,
    false,
    true
),
(
    '40000000-0000-0000-0000-000000000037',
    'The Wealth of Nations',
    'Adam Smith',
    'economics',
    'Foundational treatise of classical economics explaining division of labor and free exchange.',
    'The foundational text of modern market economics.',
    'How do individual self-interested transactions aggregate into societal prosperity?',
    'The invisible hand aligns private effort with public market wealth.',
    'It is not from the benevolence of the butcher, the brewer, or the baker that we expect our dinner, but from their regard to their own interest.

Smith demonstrates how specialization and free exchange generate national economic wealth.',
    'https://www.gutenberg.org/ebooks/3300',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['economics', 'markets', 'adam smith', 'capital'],
    '#17191D',
    false,
    false,
    true
),
(
    '40000000-0000-0000-0000-000000000038',
    'Risk, Uncertainty and Profit',
    'Frank H. Knight',
    'economics',
    'Crucial distinction between measurable statistical risk and unmeasurable genuine uncertainty.',
    'Establishes the distinction between insurable statistical risk and true uncalculable uncertainty.',
    'Why is entrepreneurial profit earned specifically by bearing unmeasurable uncertainty?',
    'Profit arises from true uncertainty, which cannot be calculated or insured against.',
    'Knight explains that routine risk can be insured away, whereas true economic profit rewards navigating uncalculable uncertainty in competitive markets.',
    'https://www.gutenberg.org/ebooks/47854',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['economics', 'risk', 'uncertainty', 'profit'],
    '#17191D',
    false,
    true,
    true
),
(
    '40000000-0000-0000-0000-000000000039',
    'Principles of Economics',
    'Alfred Marshall',
    'economics',
    'Treatise establishing supply and demand curves, marginal utility, and market equilibrium.',
    'Synthesized classical economics into marginal analysis and price elasticity.',
    'How do buyers and sellers determine prices at the margin?',
    'Economics is a study of mankind in the ordinary business of life.',
    'Marshall synthesized classical economics into marginal analysis, supply and demand curves, and price elasticity in everyday markets.',
    'https://www.gutenberg.org/ebooks/6111',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['economics', 'microeconomics', 'supply demand'],
    '#17191D',
    false,
    false,
    true
),

-- ============================================================================
-- 10. TECHNOLOGY (technology) — 4 Verified Works
-- ============================================================================
(
    '40000000-0000-0000-0000-000000000040',
    'Computing Machinery and Intelligence',
    'Alan Turing',
    'technology',
    'Foundational 1950 paper proposing the Imitation Game (Turing Test) and machine intelligence.',
    'Introduced the Turing Test and laid the philosophical foundation for artificial intelligence.',
    'Can machines think, and how do we measure artificial intelligence?',
    'If a machine can converse indistinguishably from a human, it exhibits intelligence.',
    'I propose to consider the question: Can machines think?

Turing outlines the Imitation Game to evaluate whether digital computers can emulate human cognitive responses.',
    'https://archive.org/details/turing-1950-mind',
    'Internet Archive',
    'archive',
    'intermediate',
    'paper',
    ARRAY['technology', 'ai', 'turing test', 'computation'],
    '#17191D',
    true,
    false,
    true
),
(
    '40000000-0000-0000-0000-000000000041',
    'A Mathematical Theory of Communication',
    'Claude E. Shannon',
    'technology',
    'Foundational paper establishing Information Theory, binary bits, and entropy.',
    'The foundational paper of the digital information age, defining the mathematical bit.',
    'How do we measure information mathematically across noisy communication channels?',
    'The fundamental problem of communication is reproducing at one point a message selected at another.',
    'Shannon defined the mathematical bit and information entropy, laying the groundwork for digital communications and data storage.',
    'https://archive.org/details/shannon1948',
    'Internet Archive',
    'archive',
    'advanced',
    'paper',
    ARRAY['technology', 'information theory', 'bits', 'shannon'],
    '#17191D',
    false,
    false,
    true
),
(
    '40000000-0000-0000-0000-000000000042',
    'First Draft of a Report on the EDVAC',
    'John von Neumann',
    'technology',
    'Foundational design document establishing the stored-program computer architecture.',
    'Established the Von Neumann architecture used by almost all modern microprocessors.',
    'How can computer instructions and data be stored together in single unified memory?',
    'Automatic digital computing systems require unified memory for both instructions and data.',
    'Von Neumann outlined CPU control units, memory units, and arithmetic logic, defining computer architecture.',
    'https://archive.org/details/firstdraftofrepo00vonn',
    'Internet Archive',
    'archive',
    'advanced',
    'document',
    ARRAY['technology', 'computer architecture', 'hardware'],
    '#17191D',
    false,
    true,
    true
),
(
    '40000000-0000-0000-0000-000000000043',
    'As We May Think',
    'Vannevar Bush',
    'technology',
    'Prophetic 1945 essay predicting personal computers, hypertext, and global digital knowledge networks.',
    'Visionary essay predicting the World Wide Web, personal knowledge bases, and hypertext.',
    'How will human civilization organize and query the exponentially growing mountain of research?',
    'Wholly new forms of encyclopedias will appear, ready made with a mesh of associative trails.',
    'Vannevar Bush proposed the Memex device, anticipating hyperlinked digital information retrieval long before personal computers existed.',
    'https://archive.org/details/aswemaythink1945',
    'Internet Archive',
    'archive',
    'beginner',
    'essay',
    ARRAY['technology', 'hypertext', 'memex', 'future of computing'],
    '#17191D',
    false,
    false,
    true
);
