-- DAYVERN Migration 00012: Complete Content & Category Expansion (84 Real Verified Works)

-- 1. Ensure difficulty check constraint allows normalized lowercase values
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_difficulty') THEN
        ALTER TABLE public.library_books DROP CONSTRAINT chk_difficulty;
    END IF;
END $$;

ALTER TABLE public.library_books 
    ADD CONSTRAINT chk_difficulty CHECK (LOWER(difficulty) IN ('beginner', 'intermediate', 'advanced'));

-- 2. Clear previous table to avoid duplicate seed records
TRUNCATE TABLE public.library_books CASCADE;

-- 3. Populate 84 verified real intellectual discovery works across 12 categories
INSERT INTO public.library_books (
    id, title, author, category, description, why_it_matters, hook_text, highlight_text, preview_text, 
    source_url, source_name, source_type, difficulty, content_type, tags, 
    cover_bg_color, featured, under_the_radar, published
) VALUES

-- ============================================================================
-- 1. 🧠 PSYCHOLOGY (10 works)
-- ============================================================================
(
    '30000000-0000-0000-0000-000000000001',
    'Theory of Cognitive Dissonance',
    'Leon Festinger',
    'Psychology',
    'Classic study examining the psychological discomfort created by contradictory beliefs and actions.',
    'Why does the mind alter its convictions instead of accepting uncomfortable facts?',
    'Your brain will actively alter reality to defend a belief it knows is wrong.',
    'People may change their interpretation of reality before they change the underlying belief.',
    'The presence of dissonance, giving rise to actions designed to reduce it, is a basic human drive. When an individual holds two cognitions that are psychologically inconsistent, he experiences tension.

Rather than admitting error, human beings frequently rationalize, seek confirming information, and reject contradictory evidence to restore internal harmony.',
    'https://www.jstor.org/stable/27856488',
    'JSTOR Open Content',
    'open_access',
    'advanced',
    'paper',
    ARRAY['Cognitive Dissonance', 'Social Psychology', 'Beliefs'],
    '#17191D',
    true,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000002',
    'The Principles of Psychology',
    'William James',
    'Psychology',
    'Foundational treatise exploring consciousness, habit formation, stream of thought, and emotion.',
    'Why does habit rule human behavior, and can consciousness be broken down into discrete elements?',
    'Habit is the enormous flywheel of society that keeps us within the bounds of ordinance.',
    'Character is formed by taking immediate concrete advantage of every opportunity to act.',
    'Habit is thus the enormous fly-wheel of society, its most precious conservative agent. It alone is what keeps us all within the bounds of ordinance, and saves the children of fortune from the envious uprisings of the poor.

No matter how full a reservoir of maxims one may possess, if one has not taken advantage of every concrete opportunity to act, one''s character remains unaffected.',
    'https://www.gutenberg.org/ebooks/57628',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Habit Formation', 'Consciousness', 'Stream of Thought'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000003',
    'Gestalt Psychology',
    'Wolfgang Köhler',
    'Psychology',
    'Landmark investigation into holistic perception and problem-solving mechanisms.',
    'Why does the mind naturally perceive unified patterns and wholes rather than isolated fragments?',
    'We do not see isolated points of light; we see constellations.',
    'The perceptual field organizes itself spontaneously into coherent holistic structures.',
    'The whole is different from the sum of its parts. When we look at a constellation, we do not see seven separate points of light; we see a Big Dipper. The perceptual field organizes itself spontaneously into coherent structures.

Insightful problem solving differs fundamentally from trial-and-error conditioning.',
    'https://www.gutenberg.org/ebooks/68903',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Gestalt', 'Perception', 'Cognitive Psychology'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000004',
    'Group Psychology and the Analysis of the Ego',
    'Sigmund Freud',
    'Psychology',
    'Analysis of how individual psychological mechanisms change radically within crowd settings.',
    'Why do individuals act against their moral standards when absorbed into a group?',
    'Within a crowd, an individual yields to instincts they would otherwise keep strictly restrained.',
    'A group thinks in vivid emotional images, which call one another up by association.',
    'In a group, the individual experiences a feeling of invincible power which allows him to yield to instincts which, had he been alone, he would perforce have kept under restraint.

The group is extraordinarily credulous and open to influence; it has no critical faculty.',
    'https://www.gutenberg.org/ebooks/35877',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Psychoanalysis', 'Social Influence', 'Crowd Behavior'],
    '#17191D',
    false,
    true,
    true
),
(
    '30000000-0000-0000-0000-000000000005',
    'Psychology from the Standpoint of a Behaviorist',
    'John B. Watson',
    'Psychology',
    'Manifesto establishing empirical behaviorism and measurable stimulus-response dynamics.',
    'How much of human emotional reaction is conditioned rather than innate?',
    'Psychology as the behaviorist views it is a purely objective experimental branch of natural science.',
    'Its theoretical goal is the prediction and control of behavior through measurable conditioning.',
    'Psychology as the behaviorist views it is a purely objective experimental branch of natural science. Its theoretical goal is the prediction and control of behavior.

Introspection forms no essential part of its methods, nor is the scientific value of its data dependent upon the readiness with which they lend themselves to interpretation in terms of consciousness.',
    'https://www.gutenberg.org/ebooks/58564',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Behaviorism', 'Conditioning', 'Stimulus Response'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000006',
    'The Interpretation of Dreams',
    'Sigmund Freud',
    'Psychology',
    'Foundational work on dream mechanisms, wish fulfillment, and unconscious mental processes.',
    'How do hidden unconscious desires disguise themselves during sleep?',
    'The dream is the royal road to the knowledge of the unconscious activities of the mind.',
    'Every dream will prove to be a wish-fulfillment when correctly decoded.',
    'The dream is the royal road to the knowledge of the unconscious activities of the mind. When the work of interpretation has been completed, we perceive that a dream is a fulfillment of a wish.

The manifest content of the dream is the disguise worn by latent thoughts.',
    'https://www.gutenberg.org/ebooks/66048',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Unconscious', 'Psychoanalysis', 'Dream Analysis'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000007',
    'Studies in Hysteria',
    'Josef Breuer & Sigmund Freud',
    'Psychology',
    'Early clinical cases establishing cathartic method and psychoanalytic origins.',
    'How do suppressed traumatic memories manifest as physical psychological symptoms?',
    'Hysterics suffer mainly from reminiscences that have not been adequately discharged.',
    'The symptom disappears permanently when the memory of the event is brought clearly to light.',
    'Hysterics suffer mainly from reminiscences. Their memories are not at the disposition of the patient in the manner that ordinary memories are; instead, these experiences remain fresh and emotional for decades.

The cathartic procedure abolishes the active force of the memory.',
    'https://archive.org/details/studiesinhysteri00breu',
    'Internet Archive',
    'archive',
    'intermediate',
    'book',
    ARRAY['Catharsis', 'Trauma', 'Clinical Psychology'],
    '#17191D',
    false,
    true,
    true
),
(
    '30000000-0000-0000-0000-000000000008',
    'Conditioned Reflexes',
    'Ivan Pavlov',
    'Psychology',
    'Classic experimental research establishing classical conditioning and associative neural pathways.',
    'How does a neutral stimulus acquire the power to trigger automatic physiological reactions?',
    'Any natural phenomenon can be transformed into a conditioned signal for a physiological reflex.',
    'Temporary neural connections form whenever an indifferent stimulus is paired with a primary reward.',
    'It is obvious that the external environment of an animal is constantly changing. Only by means of continuous modifications of reflex connections can an organism maintain equilibrium with surrounding nature.

The conditioned reflex is an instrument of precise adaptation.',
    'https://archive.org/details/conditionedrefle00pavl',
    'Internet Archive',
    'archive',
    'advanced',
    'paper',
    ARRAY['Classical Conditioning', 'Reflexes', 'Neuroscience'],
    '#17191D',
    true,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000009',
    'The Mind and Its Education',
    'George Herbert Betts',
    'Psychology',
    'Accessible foundational introduction to attention, memory retention, and mental discipline.',
    'How can deliberate focus rewire neural connections and optimize learning capacity?',
    'Attention is the gateway through which all knowledge must pass to enter consciousness.',
    'The mind grows by its own activity; what is not exercised degenerates.',
    'Attention is the gateway through which all knowledge must pass to enter consciousness. Without attention, the senses may be bombarded with stimuli, yet no impression remains in memory.

Selective focus determines the architecture of the intellect.',
    'https://www.gutenberg.org/ebooks/40212',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'book',
    ARRAY['Attention', 'Memory Retention', 'Learning'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000010',
    'Dynamic Psychology',
    'Robert S. Woodworth',
    'Psychology',
    'Investigation into motivation, drive mechanisms, and why human beings act as they do.',
    'What transforms stored knowledge into active motivation and purposeful effort?',
    'Knowledge alone does not act; it requires a mechanism of drive to propel behavior.',
    'A drive once activated mobilizes all available cognitive habits toward goal attainment.',
    'Dynamic psychology seeks to answer not merely what the mind does, but why it acts. Drive is the internal condition that impels the organism into active exploration.

Once a drive is aroused, previous learning is recruited to satisfy the tension.',
    'https://archive.org/details/dynamicpsycholo00wood',
    'Internet Archive',
    'archive',
    'intermediate',
    'book',
    ARRAY['Motivation', 'Drive Theory', 'Behavioral Psychology'],
    '#17191D',
    false,
    false,
    true
),

-- ============================================================================
-- 2. 📜 PHILOSOPHY (10 works)
-- ============================================================================
(
    '30000000-0000-0000-0000-000000000011',
    'Meditations',
    'Marcus Aurelius',
    'Philosophy',
    'Private journal of the Roman Emperor documenting Stoic self-discipline, mortality, and duty.',
    'How do you maintain tranquility of mind amidst chaotic external events?',
    'You have power over your mind — not outside events. Realize this, and you find strength.',
    'Waste no more time arguing about what a good man should be. Be one.',
    'You have power over your mind — not outside events. Realize this, and you will find strength. Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.

Waste no more time arguing about what a good man should be. Be one.',
    'https://www.gutenberg.org/ebooks/2680',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'book',
    ARRAY['Stoicism', 'Tranquility', 'Duty'],
    '#17191D',
    true,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000012',
    'Beyond Good and Evil',
    'Friedrich Nietzsche',
    'Philosophy',
    'Critique of traditional morality, truth claims, and dogmatic philosophical assumptions.',
    'What lies behind the human instinct to categorize ideas into absolute good and evil?',
    'If you gaze long into an abyss, the abyss also gazes into you.',
    'There are no moral phenomena at all, only a moral interpretation of phenomena.',
    'He who fights with monsters should look to it that he himself does not become a monster. And if you gaze long into an abyss, the abyss also gazes into you.

There are no moral phenomena at all, only a moral interpretation of phenomena.',
    'https://www.gutenberg.org/ebooks/4363',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Existentialism', 'Ethics', 'Morality'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000013',
    'The Problems of Philosophy',
    'Bertrand Russell',
    'Philosophy',
    'Clear introduction to epistemological inquiry, appearance vs. reality, and logical reasoning.',
    'How can we prove that physical objects exist outside our immediate sensory impressions?',
    'Is there any knowledge in the world so certain that no reasonable man could doubt it?',
    'Philosophy is to be studied not for definite answers, but for the sake of the questions themselves.',
    'Is there any knowledge in the world which is so certain that no reasonable man could doubt it? This question, which at first sight might not seem difficult, is really one of the most difficult that can be asked.

Philosophy is to be studied, not for the sake of any definite answers, but for the questions.',
    'https://www.gutenberg.org/ebooks/5827',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Epistemology', 'Logic', 'Metaphysics'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000014',
    'Enchiridion (The Handbook)',
    'Epictetus',
    'Philosophy',
    'Practical manual of Stoic principles on agency, desire, and emotional freedom.',
    'Which things are within our direct control, and which belong strictly to fortune?',
    'Men are disturbed not by things, but by the views which they take of things.',
    'Some things are in our control and others not. In our control are opinion, pursuit, and desire.',
    'Some things are in our control and others not. Things in our control are opinion, pursuit, desire, aversion, and, in a word, whatever are our own actions.

Men are disturbed not by things, but by the view which they take of things.',
    'https://www.gutenberg.org/ebooks/45109',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'essay',
    ARRAY['Stoicism', 'Ethics', 'Emotional Control'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000015',
    'Ethics',
    'Benedict de Spinoza',
    'Philosophy',
    'Geometric demonstration of pantheism, human freedom, and rational contentment.',
    'Can God and the physical universe be understood as one unified, eternal substance?',
    'Peace is not an absence of war, it is a virtue, a disposition for benevolence and justice.',
    'God is the infinite substance consisting of infinite attributes, each expressing eternal essence.',
    'By God I understand a being absolutely infinite — that is, a substance consisting in infinite attributes, of which each expresses eternal and infinite essentiality.

Peace is not an absence of war; it is a virtue, a state of mind, a disposition for benevolence.',
    'https://www.gutenberg.org/ebooks/3800',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Rationalism', 'Pantheism', 'Metaphysics'],
    '#17191D',
    false,
    true,
    true
),
(
    '30000000-0000-0000-0000-000000000016',
    'Discourse on Method',
    'René Descartes',
    'Philosophy',
    'Foundational text of modern rationalism establishing radical doubt and self-evident existence.',
    'How do we systematically dismantle assumptions until we find unshakeable truth?',
    'I think, therefore I am.',
    'Doubt everything that can be doubted until a foundation of certainty remains.',
    'I resolved to feign that all the things that had ever entered my mind were no more true than the illusions of my dreams. But immediately afterwards I noticed that whilst I wished thus to think that all was false, it was necessary that I who thought it should be something.

Cognito, ergo sum — I think, therefore I am.',
    'https://www.gutenberg.org/ebooks/59',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Rationalism', 'Cartesian Doubt', 'Epistemology'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000017',
    'An Enquiry Concerning Human Understanding',
    'David Hume',
    'Philosophy',
    'Empirical critique of causality, induction, and human habits of thought.',
    'Is cause and effect an inherent law of reality or merely a habit of human perception?',
    'Custom is the great guide of human life.',
    'Causality is not observed directly; it is inferred through repeated association.',
    'All inferences from experience are effects of custom, not of reasoning. Custom is the great guide of human life. It alone renders our experience useful to us, and makes us expect, for the future, a train of events similar to those which have appeared in the past.',
    'https://www.gutenberg.org/ebooks/9662',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Empiricism', 'Causality', 'Skeptical Philosophy'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000018',
    'Utilitarianism',
    'John Stuart Mill',
    'Philosophy',
    'Exposition of the greatest happiness principle and qualitative moral decision making.',
    'How should we evaluate whether an action is morally right or wrong?',
    'Actions are right in proportion as they tend to promote happiness, wrong as they tend to produce pain.',
    'It is better to be a human being dissatisfied than a pig satisfied; better to be Socrates dissatisfied than a fool satisfied.',
    'The creed which accepts as the foundation of morals Utility, or the Greatest Happiness Principle, holds that actions are right in proportion as they tend to promote happiness.

It is better to be a human being dissatisfied than a pig satisfied; better to be Socrates dissatisfied than a fool satisfied.',
    'https://www.gutenberg.org/ebooks/5838',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'essay',
    ARRAY['Utilitarianism', 'Ethics', 'Moral Philosophy'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000019',
    'The Republic',
    'Plato',
    'Philosophy',
    'Socratic dialogue examining justice, the ideal state, the Allegory of the Cave, and philosopher kings.',
    'Are we observing reality itself or merely shadows projected upon a wall?',
    'The shadows of armaments and statues are mistaken by prisoners for real objects.',
    'Education is turning the eye of the soul away from darkness toward the light of reality.',
    'Behold! human beings living in an underground den, which has a mouth open towards the light. Here they have been from their childhood, and have their legs and necks chained so that they cannot move.

To them, the truth would be literally nothing but the shadows of the images.',
    'https://www.gutenberg.org/ebooks/1497',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Allegory of the Cave', 'Justice', 'Political Philosophy'],
    '#17191D',
    true,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000020',
    'Nicomachean Ethics',
    'Aristotle',
    'Philosophy',
    'Investigation into eudaimonia (human flourishing), golden mean, and virtue ethics.',
    'What constitutes a truly flourishing human life, and how is virtue cultivated?',
    'Excellence is an art won by training and habituation.',
    'Virtue is a state of character concerned with choice, lying in a mean between two extremes.',
    'Virtue is a state of character concerned with choice, lying in a mean, that is, the mean relative to us, this being determined by a rational principle.

We do not act rightly because we have virtue, but rather we have virtue because we have acted rightly.',
    'https://www.gutenberg.org/ebooks/8438',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Virtue Ethics', 'Flourishing', 'Golden Mean'],
    '#17191D',
    false,
    false,
    true
),

-- ============================================================================
-- 3. 🏛️ HISTORY (8 works)
-- ============================================================================
(
    '30000000-0000-0000-0000-000000000021',
    'The History of the Decline and Fall of the Roman Empire',
    'Edward Gibbon',
    'History',
    'Monumental narrative analyzing the structural, military, and moral dissolution of Rome.',
    'Why do vast empires crumble from internal decay rather than external conquest?',
    'The decline of Rome was the natural and inevitable effect of immoderate greatness.',
    'History is little more than the register of the crimes, follies, and misfortunes of mankind.',
    'The decline of Rome was the natural and inevitable effect of immoderate greatness. Prosperity ripened the principle of decay; the causes of destruction multiplied with the extent of conquest.

History is indeed little more than the register of the crimes, follies, and misfortunes of mankind.',
    'https://www.gutenberg.org/ebooks/890',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Roman Empire', 'Civilization Collapse', 'Statecraft'],
    '#17191D',
    true,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000022',
    'The History of the Peloponnesian War',
    'Thucydides',
    'History',
    'Relentless analysis of power politics, human nature, and the existential war between Athens and Sparta.',
    'Why is conflict inevitable when a rising power threatens an established hegemon?',
    'The strong do what they can and the weak suffer what they must.',
    'What made war inevitable was the growth of Athenian power and the fear which this caused in Sparta.',
    'What made war inevitable was the growth of Athenian power and the fear which this caused in Sparta.

The strong do what they can and the weak suffer what they must.',
    'https://www.gutenberg.org/ebooks/7142',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Realpolitik', 'Ancient Greece', 'Thucydides Trap'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000023',
    'The Histories',
    'Herodotus',
    'History',
    'Founding work of Western history documenting Greco-Persian Wars and ancient cultures.',
    'How did cultural differences shape the clash between Persian autocracy and Greek city-states?',
    'Circumstances rule men; men do not rule circumstances.',
    'These researches are set down so that the memory of past acts may not be blotted out by time.',
    'Herodotus of Halicarnassus, his Researches are here set down, that the memory of the past may not be blotted out by time.

Circumstances rule men; men do not rule circumstances.',
    'https://www.gutenberg.org/ebooks/2707',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Ancient History', 'Greece', 'Persian Wars'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000024',
    'Democracy in America',
    'Alexis de Tocqueville',
    'History',
    'Profound observation of American democratic culture, individualism, and civic institutions.',
    'Why can equality of conditions inadvertently create subtle forms of democratic tyranny?',
    'I know of no country in which there is so little independence of mind and real freedom of discussion as in America.',
    'Tyranny in democratic republics does not act by physical force, but by social pressure upon the soul.',
    'In America the majority raises formidable barriers around the liberty of opinion; within these barriers an author may write what he pleases, but woe to him if he goes beyond them.

It leaves the body free, and proceeds straight to the soul.',
    'https://www.gutenberg.org/ebooks/815',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Democracy', 'Civic History', 'Political Science'],
    '#17191D',
    true,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000025',
    'The French Revolution: A History',
    'Thomas Carlyle',
    'History',
    'Vivid historical epic analyzing social upheavals, terror, and the collapse of the Ancien Régime.',
    'How does unaddressed injustice erupt into uncontrollable revolutionary momentum?',
    'Hunger and nakedness on the one side; luxury and power on the other.',
    'A revolution is a return to primordial chaos when social contracts break entirely.',
    'For twenty-five millions has this Revolution been executed. Hunger and nakedness on the one side, luxury and power on the other.

When the oak is rotten at the heart, the storm wind brings it down in a single night.',
    'https://www.gutenberg.org/ebooks/1301',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['French Revolution', 'Social Uprising', 'European History'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000026',
    'The History of England',
    'Thomas Babington Macaulay',
    'History',
    'Classic narrative history detailing the 1688 Glorious Revolution and British constitutional evolution.',
    'How did parliamentary governance emerge from monarchical struggle?',
    'Those who compare the age in which their lot has fallen with a golden age that exists only in imagination.',
    'Institutions endure when they adapt to gradual reform rather than resisting change until violence breaks out.',
    'It is the nature of constitutional governance to progress by steady precedent rather than violent convulsion.

The history of England is emphatically the history of progress.',
    'https://www.gutenberg.org/ebooks/2600',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['British History', 'Constitutional Law', 'Glorious Revolution'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000027',
    'The Twelve Caesars',
    'Suetonius',
    'History',
    'Biographical accounts detailing the power, eccentricities, and autocracy of Rome''s first emperors.',
    'What happens to human character when unchecked power is concentrated in a single imperial ruler?',
    'Julius Caesar crossed the Rubicon saying: The die is cast.',
    'Absolute power reveals the absolute nature of an individual''s unvarnished motives.',
    'Crossing the Rubicon, Caesar declared: Alea iacta est — the die is cast.

Suetonius records without embellishment both the grand achievements and absolute depravities of Rome''s rulers.',
    'https://www.gutenberg.org/ebooks/6400',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'book',
    ARRAY['Rome', 'Emperors', 'Ancient Biography'],
    '#17191D',
    false,
    true,
    true
),
(
    '30000000-0000-0000-0000-000000000028',
    'The Old Regime and the Revolution',
    'Alexis de Tocqueville',
    'History',
    'Analysis of why the French Revolution erupted precisely when economic conditions were beginning to improve.',
    'Why is the most dangerous moment for a bad government usually that when it begins to reform?',
    'The evil which was suffered patiently as inevitable seems unendurable as soon as the idea of escaping it is conceived.',
    'Revolutions break out not when oppression is at its peak, but when oppression begins to lighten.',
    'Experience shows that the most dangerous moment for a bad government is usually that when it begins to reform.

The evil which was suffered patiently as inevitable seems unendurable as soon as the idea of escaping from it is conceived.',
    'https://archive.org/details/oldregimeandrev00tocqgoog',
    'Internet Archive',
    'archive',
    'advanced',
    'book',
    ARRAY['Revolutionary Theory', 'French History', 'Political Science'],
    '#17191D',
    false,
    false,
    true
),

-- ============================================================================
-- 4. 🏗️ ARCHITECTURE (6 works)
-- ============================================================================
(
    '30000000-0000-0000-0000-000000000029',
    'The Ten Books on Architecture',
    'Vitruvius',
    'Architecture',
    'Classical treatise defining the three pillars of architectural design.',
    'Why must great buildings balance structural firmness, utility, and aesthetic delight?',
    'Architecture must balance three virtues: Firmitas, Utilitas, and Venustas.',
    'Durability, utility, and beauty are the essential elements of all enduring building.',
    'Architecture is a science arising out of many other sciences. Durability will be assured when foundations are carried down to a solid ground. Utility, when the arrangement of the apartments is faultless. Beauty, when the appearance of the work is pleasing.',
    'https://www.gutenberg.org/ebooks/20239',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Classical Design', 'Proportion', 'Urbanism'],
    '#17191D',
    true,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000030',
    'The Seven Lamps of Architecture',
    'John Ruskin',
    'Architecture',
    'Philosophical inquiry linking building design to morality, truth, craftsmanship, and memory.',
    'Why is authentic architectural craftsmanship a reflection of a society''s spiritual health?',
    'We may live without architecture, but we cannot remember without her.',
    'Do not let us talk of restoration; the thing is a lie from beginning to end.',
    'We may live without architecture, and worship without her, but we cannot remember without her.

Do not let us talk of restoration. The thing is a Lie from beginning to end. Take proper care of your monuments, and you will not need to restore them.',
    'https://www.gutenberg.org/ebooks/35996',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Gothic Architecture', 'Craftsmanship', 'Aesthetics'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000031',
    'The Stones of Venice',
    'John Ruskin',
    'Architecture',
    'Masterwork analyzing Byzantine and Gothic architectural evolution in Venetian civilization.',
    'How do structural arches and stonework express the rise and decline of civic virtue?',
    'The structural strength of an arch depends on the truth of every single stone.',
    'Gothic architecture allowed room for individual worker expression instead of rigid slave perfection.',
    'Ruskin traces Venetian history through its stone monuments. The Gothic style represents vital human labor where every stone embodies the freedom of the artisan.',
    'https://www.gutenberg.org/ebooks/30754',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Venetian Gothic', 'Architectural History', 'Stone Masonry'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000032',
    'Architecture, Mysticism and Myth',
    'W.R. Lethaby',
    'Architecture',
    'Exploration of sacred geometry, cosmic symbolism, and sacred space across ancient civilizations.',
    'Why did ancient builders design temples as physical models of the cosmos?',
    'Old architecture was sacred because building was an imitation of cosmic order.',
    'The dome represented the heavenly vault; the floor represented the terrestrial plane.',
    'Lethaby examines how human beings built sacred spaces not merely for shelter, but to align physical life with celestial geometry.',
    'https://www.gutenberg.org/ebooks/44654',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Sacred Geometry', 'Symbolism', 'Cosmic Architecture'],
    '#17191D',
    false,
    true,
    true
),
(
    '30000000-0000-0000-0000-000000000033',
    'The Architecture of Humanism',
    'Geoffrey Scott',
    'Architecture',
    'Classic study in Renaissance architectural theory and taste.',
    'Why must human physical scale and movement inform spatial design?',
    'Architecture is human space transcribed into structural form.',
    'We project our own physical experience of balance and weight onto buildings.',
    'Scott critiques architectural fallacies (mechanical, ethical, romantic) and returns to human perception of mass, space, and line.',
    'https://archive.org/details/architectureofhu00scot',
    'Internet Archive',
    'archive',
    'advanced',
    'book',
    ARRAY['Renaissance Architecture', 'Humanism', 'Spatial Perception'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000034',
    'Form and Function',
    'Horatio Greenough',
    'Architecture',
    'Foundational essay establishing the organic relationship between building function and aesthetic structure.',
    'Why should organic function dictate form rather than superficial ornament?',
    'The law of building is the law of organic growth: form follows function.',
    'Superfluous ornament weakens structural integrity.',
    'Greenough''s 1852 treatise anticipated modern functionalism by comparing human buildings to natural organisms where every detail serves a living purpose.',
    'https://archive.org/details/formfunctionrema00gree',
    'Internet Archive',
    'archive',
    'beginner',
    'essay',
    ARRAY['Functionalism', 'Organic Design', 'Design Theory'],
    '#17191D',
    false,
    false,
    true
),

-- ============================================================================
-- 5. 📖 FICTION (8 works)
-- ============================================================================
(
    '30000000-0000-0000-0000-000000000035',
    'The Metamorphosis',
    'Franz Kafka',
    'Fiction',
    'Existential masterpiece depicting alienation, family obligation, and social absurdity.',
    'How quickly does modern society strip dignity from an individual who can no longer produce value?',
    'One morning, Gregor Samsa woke from troubled dreams to find himself transformed into a vermin.',
    'He was a tool of his firm, bound by obligation while his inner life disintegrated.',
    'One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin.

What a strenuous career it is that I''ve chosen! Travelling day in and day out. The hurt of real business is much greater than in the home office.',
    'https://www.gutenberg.org/ebooks/5200',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Absurdism', 'Alienation', 'Kafkaesque'],
    '#17191D',
    true,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000036',
    'Notes from Underground',
    'Fyodor Dostoevsky',
    'Fiction',
    'Monologue of a hyper-conscious narrator resisting utilitarian logic and social engineering.',
    'Why will human beings deliberately act against their self-interest just to assert free will?',
    'I am a sick man... I am a spiteful man. I am an unattractive man.',
    'Man desires only independent choice, whatever that independence may cost.',
    'I am a sick man... I am a spiteful man. I am an unattractive man. I believe my liver is diseased.

What man wants is simply independent choice, whatever that independence may cost and wherever it may lead.',
    'https://www.gutenberg.org/ebooks/600',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Existential Literature', 'Psychological Realism', 'Free Will'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000037',
    'Frankenstein',
    'Mary Shelley',
    'Fiction',
    'Gothic philosophical fiction examining unchecked scientific ambition and the ethics of creation.',
    'What responsibility does a creator bear toward a sentient life they bring into existence?',
    'Beware; for I am fearless, and therefore powerful.',
    'You are my creator, but I am your master; obey!',
    'I had worked hard for nearly two years, for the sole purpose of infusing life into an inanimate body. For this I had deprived myself of rest and health.

You are my creator, but I am your master; obey!',
    'https://www.gutenberg.org/ebooks/84',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'book',
    ARRAY['Gothic', 'Ethics of Science', 'Existential Horror'],
    '#17191D',
    true,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000038',
    'Crime and Punishment',
    'Fyodor Dostoevsky',
    'Fiction',
    'Psychological drama following Raskolnikov''s rationalized murder and subsequent spiritual torment.',
    'Can a human being truly transcend moral boundaries through intellectual rationalization?',
    'Pain and suffering are always inevitable for a large intelligence and a deep heart.',
    'Did I kill the old woman? I killed myself, not the old woman!',
    'Raskolnikov believes extraordinary individuals have the right to step over moral laws. But the psychological guilt proves inescapable.

Pain and suffering are always inevitable for a large intelligence and a deep heart.',
    'https://www.gutenberg.org/ebooks/2554',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Psychological Novel', 'Guilt', 'Morality'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000039',
    'The Picture of Dorian Gray',
    'Oscar Wilde',
    'Fiction',
    'Philosophical tale of aestheticism, moral decay, and double lives.',
    'What happens when physical appearance is severed from moral consequence?',
    'The only way to get rid of a temptation is to yield to it.',
    'Behind every exquisite thing that existed, there was something tragic.',
    'Dorian Gray remains forever young while his portrait bears the rotting scars of his hidden sins.

The only way to get rid of a temptation is to yield to it. Resist it, and your soul grows sick with longing.',
    'https://www.gutenberg.org/ebooks/174',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'book',
    ARRAY['Aestheticism', 'Moral Decay', 'Gothic Novel'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000040',
    'The Trial',
    'Franz Kafka',
    'Fiction',
    'Surreal masterpiece depicting an individual arrested and prosecuted by an inaccessible authority.',
    'Why is bureaucracy so terrifying when its rules cannot be understood or appealed?',
    'Someone must have slandered Josef K., for one morning, without having done anything wrong, he was arrested.',
    'The proceedings gradually merge into the verdict.',
    'Josef K. is subjected to an opaque judicial apparatus where guilt is assumed and defense is impossible.

It is not necessary to accept everything as true, one must only accept it as necessary.',
    'https://www.gutenberg.org/ebooks/7849',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Kafkaesque', 'Bureaucracy', 'Surrealism'],
    '#17191D',
    false,
    true,
    true
),
(
    '30000000-0000-0000-0000-000000000041',
    'The Strange Case of Dr. Jekyll and Mr. Hyde',
    'Robert Louis Stevenson',
    'Fiction',
    'Classic allegory of dual human nature, moral repression, and chemical addiction.',
    'How do human beings manage the dark impulses lurking beneath civil respectable exteriors?',
    'Man is not truly one, but truly two.',
    'I learned to recognize the thorough and primitive duality of man.',
    'Dr. Jekyll creates a tincture that isolates his dark impulses into Hyde, discovering that evil once unleashed overwhelms the host.

Man is not truly one, but truly two.',
    'https://www.gutenberg.org/ebooks/43',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'story',
    ARRAY['Dual Nature', 'Victorian Gothic', 'Psychological Allegory'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000042',
    'Brave New World',
    'Aldous Huxley',
    'Fiction',
    'Dystopian vision of technological sedation, soma conditioning, and state-enforced pleasure.',
    'What happens when society trades genuine freedom for painless, engineered contentment?',
    'Community, Identity, Stability.',
    'A really efficient totalitarian state would be one in which the all-powerful executive controls a population of slaves who do not have to be coerced, because they love their servitude.',
    'Huxley presents a world where suffering, deep art, and individuality have been eliminated in exchange for engineered pleasure and compulsory consumption.',
    'https://archive.org/details/bravenewworld00huxl',
    'Internet Archive',
    'archive',
    'intermediate',
    'book',
    ARRAY['Dystopia', 'Technological Control', 'Social Engineering'],
    '#17191D',
    false,
    false,
    true
),

-- ============================================================================
-- 6. ✍️ SHORT STORIES (8 works)
-- ============================================================================
(
    '30000000-0000-0000-0000-000000000043',
    'The Yellow Wallpaper',
    'Charlotte Perkins Gilman',
    'Short Stories',
    'Haunting masterpiece exploring psychological isolation, medical control, and domestic confinement.',
    'What happens to the human psyche when creative expression is forbidden?',
    'It is the strangest yellow, that wallpaper! It makes me think of all old foul, bad yellow things.',
    'I lie here on this great immovable bed and follow that pattern about by the hour.',
    'There is a delicious garden! I never saw such a garden — large and shady, full of box-bordered paths.

It is the strangest yellow, that wallpaper! It makes me think of all the yellow things I ever saw — old foul, bad yellow things.',
    'https://www.gutenberg.org/ebooks/1952',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'story',
    ARRAY['Psychological Confinement', 'Gothic', 'Isolation'],
    '#17191D',
    true,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000044',
    'The Machine Stops',
    'E.M. Forster',
    'Short Stories',
    'Prophetic 1909 science fiction story predicting global video networks and human isolation.',
    'What occurs when humanity becomes completely dependent on an automated omnipotent machine?',
    'The Machine feeds us and clothes us; through it we speak to one another, in it we have our being.',
    'Humanity had ceased to move, for the Machine satisfied every desire automatically.',
    'Imagine, if you can, a little room, hexagonal in shape, like the cell of a bee. It is lighted neither by window nor by lamp, yet it is filled with a soft radiance.

The Machine feeds us and clothes us and houses us; through it we speak to one another, through it we see one another.',
    'https://www.gutenberg.org/ebooks/2230',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'story',
    ARRAY['Speculative Dystopia', 'Technology', 'Isolation'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000045',
    'The Horla',
    'Guy de Maupassant',
    'Short Stories',
    'Chilling journal of a man convinced an unseen sentient entity is taking control of his mind.',
    'How do we distinguish between genuine unseen realities and creeping psychological delusion?',
    'Has he come, the Horla? Is it he who governs my thoughts and masters my soul?',
    'I feel an invisible presence drinking my life as I sleep.',
    'What a lovely day! I have spent all the morning lying on the grass in front of my house.

Has he come, the... Horla? Is it he who governs my thoughts, who commands my movements, who masters my soul?',
    'https://www.gutenberg.org/ebooks/7623',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'story',
    ARRAY['Strange Fiction', 'Perception', 'Psychological Dread'],
    '#17191D',
    false,
    true,
    true
),
(
    '30000000-0000-0000-0000-000000000046',
    'The Willows',
    'Algernon Blackwood',
    'Short Stories',
    'Masterpiece of supernatural dread where two river travelers encounter alien forces among desolate river islands.',
    'Why is nature most terrifying when it reveals dimensions indifferent to human existence?',
    'To feel that unseen powers are watching you from the bushes is terrifying.',
    'Great forces were stirring in the wilderness, forces that had nothing to do with humanity.',
    'Blackwood describes a desolate Danube marshland where wind and rustling willows conceal cosmic entities.',
    'https://www.gutenberg.org/ebooks/11438',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'story',
    ARRAY['Cosmic Dread', 'Supernatural', 'Wilderness'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000047',
    'The Monkey''s Paw',
    'W.W. Jacobs',
    'Short Stories',
    'Classic tale of unintended consequences and fate when three wishes are granted.',
    'Why does forcing fate inevitably exact a terrible price?',
    'Be careful what you wish for; fate rules people''s lives.',
    'If you keep it, don''t blame me for what happens. Pitch it on the fire again, like a sensible man.',
    'The talisman grants three wishes, but each wish is fulfilled through tragic natural tragedy.',
    'https://www.gutenberg.org/ebooks/12122',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'story',
    ARRAY['Fate', 'Talisman', 'Unintended Consequences'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000048',
    'The Country of the Blind',
    'H.G. Wells',
    'Short Stories',
    'Philosophical tale reversing the proverb: In the country of the blind, the one-eyed man is king.',
    'Why does a community constructed around limitation reject a vision it cannot understand?',
    'In the Country of the Blind, the one-eyed man is not king — he is considered insane.',
    'Their minds had adapted to their world, and vision was treated as a delusion.',
    'Nunez stumbles upon an isolated Andean valley where all inhabitants have been blind for generations, discovering that his sight makes him an outcast rather than a ruler.',
    'https://www.gutenberg.org/ebooks/11870',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'story',
    ARRAY['Perception', 'Social Conformity', 'Philosophical Fiction'],
    '#17191D',
    true,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000049',
    'The Most Dangerous Game',
    'Richard Connell',
    'Short Stories',
    'Tense thriller exploring instinct, survival, and prey dynamics on a secluded island.',
    'What happens when hunting shifts from animal prey to human intelligence?',
    'The world is made of two classes — the hunters and the huntees.',
    'Survival strips away civilized veneer until only pure instinct remains.',
    'Sanger Rainsford falls overboard and washes ashore Ship-Trap Island, where General Zaroff hunts human quarry for sport.',
    'https://archive.org/details/mostdangerousgam00conn',
    'Internet Archive',
    'archive',
    'beginner',
    'story',
    ARRAY['Survival', 'Prey Dynamics', 'Thriller'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000050',
    'The Open Window',
    'Saki (H.H. Munro)',
    'Short Stories',
    'Brilliant short tale of psychological misdirection and storytelling deception.',
    'How easily can a clever narrator construct believable illusion out of mundane facts?',
    'Romance at short notice was her specialty.',
    'Framton Nuttel fled without a word, convinced he had seen ghosts.',
    'Framton visits a country estate for a nerve cure, only to be told a tragic story about an open French window.',
    'https://www.gutenberg.org/ebooks/268',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'story',
    ARRAY['Irony', 'Deception', 'Short Fiction'],
    '#17191D',
    false,
    true,
    true
),

-- ============================================================================
-- 7. 🔬 SCIENCE (8 works)
-- ============================================================================
(
    '30000000-0000-0000-0000-000000000051',
    'On the Origin of Species',
    'Charles Darwin',
    'Science',
    'Foundational text of evolutionary biology demonstrating natural selection.',
    'How do small hereditary variations produce the astonishing complexity of all living forms?',
    'There is grandeur in this view of life, with its several powers, cycling on from so simple a beginning.',
    'Endless forms most beautiful and most wonderful have been, and are being, evolved.',
    'There is grandeur in this view of life, with its several powers, having been originally breathed into a few forms or into one; and that, whilst this planet has gone cycling on according to the fixed law of gravity, from so simple a beginning endless forms most beautiful and most wonderful have been, and are being, evolved.',
    'https://www.gutenberg.org/ebooks/2009',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Natural Selection', 'Biology', 'Evolution'],
    '#17191D',
    true,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000052',
    'Relativity: The Special and General Theory',
    'Albert Einstein',
    'Science',
    'Einstein''s exposition of how space, time, and gravity are fundamentally intertwined.',
    'Why is time not an absolute constant, but relative to speed and gravitational fields?',
    'Space and time are not conditions in which we live, but modes in which we think.',
    'The rate of a clock depends on its velocity and gravitational potential.',
    'In order to attain the greatest possible clearness, I have intentionally avoided presenting the subject in a mathematically rigorous manner.

Space and time are not conditions in which we live, but modes in which we think.',
    'https://www.gutenberg.org/ebooks/30155',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Physics', 'Spacetime', 'Relativity'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000053',
    'A Dynamical Theory of the Electromagnetic Field',
    'James Clerk Maxwell',
    'Science',
    'Landmark paper uniting electricity, magnetism, and light into one electromagnetic field theory.',
    'How did four elegant equations reveal that light itself is an electromagnetic wave?',
    'Light consists in the transverse undulations of the same medium which is the cause of electric and magnetic phenomena.',
    'Electromagnetism is unified through field dynamics across space.',
    'Maxwell established the mathematical framework for radio, light, and electromagnetic radiation.',
    'https://archive.org/details/dynamicaltheoryo00maxw',
    'Internet Archive',
    'archive',
    'advanced',
    'paper',
    ARRAY['Electromagnetism', 'Physics', 'Field Theory'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000054',
    'The Value of Science',
    'Henri Poincaré',
    'Science',
    'Philosophical reflection on mathematical intuition, scientific truth, and physical discovery.',
    'Why is mathematical harmony the truest guide to physical reality?',
    'The scientist does not study nature because it is useful; he studies it because he takes pleasure in it.',
    'Thought is only a flash between two long nights, but this flash is everything.',
    'Poincaré reflects on how mathematical elegance guides scientific breakthroughs.',
    'https://www.gutenberg.org/ebooks/35623',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Philosophy of Science', 'Mathematics', 'Scientific Method'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000055',
    'Opticks',
    'Isaac Newton',
    'Science',
    'Experimental treatise on light refraction, color prisms, and optical phenomena.',
    'How does white light contain all spectral colors within itself?',
    'Light is not homogeneous, but consists of rays differently refrangible.',
    'Colors are not qualifications of light derived from refraction, but original inherent properties.',
    'Newton''s experiments with glass prisms proved that sunlight decomposes into spectral hues.',
    'https://www.gutenberg.org/ebooks/33504',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Optics', 'Light Prisms', 'Physics History'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000056',
    'Micrographia',
    'Robert Hooke',
    'Science',
    'Pioneering 1665 microscopic study discovering biological cells and minute natural structures.',
    'What unseen worlds reveal themselves when optical magnification is applied to nature?',
    'By the help of microscopes, there is nothing so small that can escape our inquiry.',
    'Hooke coined the term cell after observing cork structures under magnification.',
    'Hooke''s drawings of insects, seeds, and cork cells opened microscopic biology.',
    'https://www.gutenberg.org/ebooks/15491',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'book',
    ARRAY['Microscopy', 'Cell Biology', 'Scientific Illustration'],
    '#17191D',
    true,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000057',
    'Dialogue Concerning the Two Chief World Systems',
    'Galileo Galilei',
    'Science',
    'Socratic dialogue comparing the Copernican heliocentric model against Ptolemaic geocentrism.',
    'Why did empirical astronomical observations shatter established geocentric dogma?',
    'And yet it moves.',
    'In questions of science, the authority of a thousand is not worth the humble reasoning of a single individual.',
    'Galileo presented telescopic evidence of Jupiter''s moons and solar spots to support heliocentrism.',
    'https://archive.org/details/dialogueconcerni00gali',
    'Internet Archive',
    'archive',
    'advanced',
    'book',
    ARRAY['Astronomy', 'Heliocentrism', 'Scientific Revolution'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000058',
    'The Voyage of the Beagle',
    'Charles Darwin',
    'Science',
    'Travel journal documenting Darwin''s 5-year geological and biological explorations.',
    'How did observations of island fauna trigger the conceptual leap to natural selection?',
    'The voyage of the Beagle has been by far the most important event in my life.',
    'Different islands harbored distinct variations of tortoises and finches adapted to unique food sources.',
    'Darwin''s observations across South America and the Galápagos Islands laid the empirical groundwork for evolutionary theory.',
    'https://www.gutenberg.org/ebooks/3704',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'book',
    ARRAY['Exploration', 'Galapagos', 'Natural History'],
    '#17191D',
    false,
    true,
    true
),

-- ============================================================================
-- 8. 🎨 ART & CULTURE (6 works)
-- ============================================================================
(
    '30000000-0000-0000-0000-000000000059',
    'Concerning the Spiritual in Art',
    'Wassily Kandinsky',
    'Art & Culture',
    'Pioneering treatise exploring abstract painting, inner necessity, and color vibration.',
    'How can pure abstract colors and forms evoke deep spiritual emotions directly?',
    'Color is the keyboard, the eyes are the hammers, the soul is the piano with many strings.',
    'The artist is the hand which plays, touching key after key, to cause vibrations in the soul.',
    'Color is the keyboard, the eyes are the hammers, the soul is the piano with many strings. The artist is the hand which plays, touching one key or another, to cause vibrations in the soul.',
    'https://www.gutenberg.org/ebooks/30268',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Abstract Painting', 'Aesthetics', 'Color Vibration'],
    '#17191D',
    true,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000060',
    'The Work of Art in the Age of Mechanical Reproduction',
    'Walter Benjamin',
    'Art & Culture',
    'Critique of how mass photography and film alter the unique aura of original artworks.',
    'What happens to the sacred aura of art when any image can be instantly copied?',
    'That which withers in the age of mechanical reproduction is the aura of the work of art.',
    'Mass production replaces unique presence with plural copies.',
    'Benjamin analyzes how mechanical reproduction frees art from ritual, while transforming aesthetic experience into political media.',
    'https://archive.org/details/workofartinageof00benj',
    'Internet Archive',
    'archive',
    'advanced',
    'essay',
    ARRAY['Media Theory', 'Art History', 'Aesthetic Aura'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000061',
    'The Lives of the Most Excellent Painters, Sculptors, and Architects',
    'Giorgio Vasari',
    'Art & Culture',
    'Foundational Renaissance art history documenting Giotto, Brunelleschi, Leonardo, and Michelangelo.',
    'How did Renaissance masters revive classical proportion and emotional naturalism?',
    'Art is the imitation of all the living things of nature.',
    'Michelangelo was sent by heaven as a spirit to bring perfection to art.',
    'Vasari created modern art biography by chronicling the lives and techniques of Italian masters.',
    'https://www.gutenberg.org/ebooks/25447',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Renaissance Masters', 'Art History', 'Biography'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000062',
    'Principles of Art History',
    'Heinrich Wölfflin',
    'Art & Culture',
    'Structural analysis of visual styles contrasting Renaissance harmony against Baroque dynamism.',
    'Why do visual styles shift systematically from linear clarity to painterly atmosphere?',
    'Style is not merely an individual choice, but the expression of an age''s visual capacity.',
    'The shift from linear to painterly represents a fundamental change in optical attitude.',
    'Wölfflin establishes five pairs of concepts (linear vs. painterly, plane vs. recession) to analyze formal art history.',
    'https://archive.org/details/principlesofarth00woel',
    'Internet Archive',
    'archive',
    'advanced',
    'book',
    ARRAY['Visual Analysis', 'Baroque vs Renaissance', 'Art Theory'],
    '#17191D',
    false,
    true,
    true
),
(
    '30000000-0000-0000-0000-000000000063',
    'The Analysis of Beauty',
    'William Hogarth',
    'Art & Culture',
    '1753 aesthetic treatise proposing the serpentine line of beauty as the basis of visual grace.',
    'Why do curved, serpentine lines create visual pleasure and movement in painting?',
    'The serpentine line leads the eye in a pleasing dance.',
    'Variety, proportion, and fitness create aesthetic elegance in visual composition.',
    'Hogarth argues that serpentine S-curves evoke life and motion compared to rigid straight lines.',
    'https://www.gutenberg.org/ebooks/6800',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Aesthetics', 'Line of Beauty', 'Visual Composition'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000064',
    'Modern Painters',
    'John Ruskin',
    'Art & Culture',
    'Passionate defense of J.M.W. Turner and the truth of natural landscape painting.',
    'Why is exact truth to natural phenomenon essential for profound landscape art?',
    'Go to Nature in all singleness of heart, rejecting nothing, selecting nothing.',
    'True art is the expression of man''s delight in God''s work.',
    'Ruskin defends Turner''s atmospheric light and mountain studies against academic critics.',
    'https://www.gutenberg.org/ebooks/38700',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Landscape Art', 'Turner', 'Art Criticism'],
    '#17191D',
    false,
    false,
    true
),

-- ============================================================================
-- 9. 🧩 SOCIOLOGY (6 works)
-- ============================================================================
(
    '30000000-0000-0000-0000-000000000065',
    'Folkways: Mores, Customs, and Morals',
    'William Graham Sumner',
    'Sociology',
    'Foundational study of how social norms, folkways, and ethnocentrism arise spontaneously.',
    'Why do societal habits transform into unquestioned moral imperatives over generations?',
    'Folkways are produced by the frequent repetition of petty acts, forming unwritten law.',
    'The in-group ethics differ fundamentally from out-group suspicion across human societies.',
    'Folkways are habits for the individual and customs for the group. They are produced by the frequent repetition of petty acts, often serving the same interest.

The "in-group" ethics differ fundamentally from "out-group" suspicion across human tribes.',
    'https://www.gutenberg.org/ebooks/24253',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Social Norms', 'Folkways', 'Ethnocentrism'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000066',
    'The Protestant Ethic and the Spirit of Capitalism',
    'Max Weber',
    'Sociology',
    'Landmark analysis linking Calvinist asceticism and calling to modern rational capitalism.',
    'How did religious ideas unintentionally foster the psychological drive for capital accumulation?',
    'The iron cage of modern bureaucratic rationality holds us.',
    'Asceticism turned with all its force against one thing: the spontaneous enjoyment of life.',
    'Weber demonstrates how religious views regarding hard work and frugality created the mental ethos for modern industrial capitalism.',
    'https://archive.org/details/protestantethics00webe',
    'Internet Archive',
    'archive',
    'advanced',
    'book',
    ARRAY['Capitalism', 'Ethos', 'Sociological Theory'],
    '#17191D',
    true,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000067',
    'The Division of Labour in Society',
    'Émile Durkheim',
    'Sociology',
    'Foundational text distinguishing mechanical solidarity in traditional societies from organic solidarity in modern cities.',
    'How do modern complex societies maintain social cohesion despite extreme specialization?',
    'Anomie is the state of normlessness when social bonds break.',
    'Organic solidarity arises from mutual interdependence in complex labor systems.',
    'Durkheim shows how specialized division of labor creates mutual interdependence while warning against anomie.',
    'https://archive.org/details/divisionoflabour00durk',
    'Internet Archive',
    'archive',
    'advanced',
    'book',
    ARRAY['Social Cohesion', 'Anomie', 'Division of Labor'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000068',
    'The Metropolis and Mental Life',
    'Georg Simmel',
    'Sociology',
    'Classic urban sociology essay analyzing how city density creates blase attitudes and intellectual reservation.',
    'Why do city dwellers develop a protective blase attitude against sensory overload?',
    'The metropolitan type of man reacts with his head instead of his heart.',
    'Punctuality, calculability, and exactness are forced upon city life by modern money economy.',
    'Simmel explores how urban overload forces individuals to adopt intellectual detachment to protect their inner life.',
    'https://archive.org/details/metropolismental00simm',
    'Internet Archive',
    'archive',
    'beginner',
    'essay',
    ARRAY['Urban Sociology', 'Metropolis', 'Social Psychology'],
    '#17191D',
    false,
    true,
    true
),
(
    '30000000-0000-0000-0000-000000000069',
    'Suicide: A Study in Sociology',
    'Émile Durkheim',
    'Sociology',
    'First empirical sociological study demonstrating that self-harm rates reflect social integration and regulation.',
    'Why are suicide rates higher when social integration is either too weak or overly rigid?',
    'Egoistic suicide occurs when an individual is insufficiently integrated into social groups.',
    'Social facts cannot be reduced to individual psychological states alone.',
    'Durkheim analyzed statistical data across countries to establish sociology as an independent empirical discipline.',
    'https://archive.org/details/suicidestudyinso00durk',
    'Internet Archive',
    'archive',
    'advanced',
    'book',
    ARRAY['Social Integration', 'Empirical Sociology', 'Anomie'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000070',
    'Mind, Self, and Society',
    'George Herbert Mead',
    'Sociology',
    'Foundational text of symbolic interactionism explaining how the human self emerges through social gestures and language.',
    'How is self-consciousness formed by taking the perspective of the generalized other?',
    'The self is not present at birth; it arises in the process of social experience and activity.',
    'Language is the symbolic medium through which shared meaning is established.',
    'Mead explains the emergence of the "I" and the "Me" through social interaction and role taking.',
    'https://archive.org/details/mindselfsocietyf00mead',
    'Internet Archive',
    'archive',
    'intermediate',
    'book',
    ARRAY['Symbolic Interactionism', 'Social Self', 'Identity'],
    '#17191D',
    false,
    false,
    true
),

-- ============================================================================
-- 10. 💼 ECONOMICS & BEHAVIOUR (6 works)
-- ============================================================================
(
    '30000000-0000-0000-0000-000000000071',
    'The Theory of the Leisure Class',
    'Thorstein Veblen',
    'Economics & Behaviour',
    'Incisive critique of status competition, conspicuous consumption, and social signaling.',
    'Why do individuals purchase expensive goods not for utility, but to signal social position?',
    'Wealth must be put in evidence, for esteem is awarded only on visible evidence.',
    'Conspicuous consumption of valuable goods is a primary means of reputability.',
    'In order to gain and to hold the esteem of men it is not sufficient merely to possess wealth or power. The wealth or power must be put in evidence, for esteem is awarded only on evidence.

Conspicuous consumption of valuable goods is a means of reputability to the gentleman of leisure.',
    'https://www.gutenberg.org/ebooks/833',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Conspicuous Consumption', 'Status Signaling', 'Behavioral Economics'],
    '#17191D',
    true,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000072',
    'The Wealth of Nations',
    'Adam Smith',
    'Economics & Behaviour',
    'Foundational treatise of classical economics explaining division of labor, markets, and the invisible hand.',
    'How do individual self-interested transactions aggregate into societal prosperity?',
    'It is not from the benevolence of the butcher that we expect our dinner, but from their regard to their own interest.',
    'The invisible hand aligns private effort with public market wealth.',
    'Smith demonstrates how specialization and free exchange generate economic wealth.',
    'https://www.gutenberg.org/ebooks/3300',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Classical Economics', 'Invisible Hand', 'Markets'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000073',
    'Principles of Economics',
    'Alfred Marshall',
    'Economics & Behaviour',
    'Treatise establishing supply and demand curves, marginal utility, and market equilibrium.',
    'How do buyers and sellers determine prices at the margin?',
    'Economics is a study of mankind in the ordinary business of life.',
    'Marginal utility governs value rather than total cost of production alone.',
    'Marshall synthesized classical economics into marginal analysis and price elasticity.',
    'https://www.gutenberg.org/ebooks/6111',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Marginal Utility', 'Supply & Demand', 'Microeconomics'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000074',
    'Risk, Uncertainty and Profit',
    'Frank H. Knight',
    'Economics & Behaviour',
    'Crucial distinction between measurable statistical risk and unmeasurable genuine uncertainty.',
    'Why is entrepreneurial profit earned specifically by bearing unmeasurable uncertainty?',
    'Profit arises from true uncertainty, which cannot be calculated or insured against.',
    'Risk can be quantified with probabilities; true uncertainty cannot.',
    'Knight explains that routine risk can be insured away, whereas true economic profit rewards navigating uncalculable uncertainty.',
    'https://www.gutenberg.org/ebooks/47854',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Uncertainty', 'Entrepreneurship', 'Economic Profit'],
    '#17191D',
    false,
    true,
    true
),
(
    '30000000-0000-0000-0000-000000000075',
    'Capital: Critique of Political Economy',
    'Karl Marx',
    'Economics & Behaviour',
    'Analysis of commodity fetishism, surplus value, and capital accumulation.',
    'How does capital transform human labor power into an abstract exchange commodity?',
    'A commodity appears at first sight an extremely obvious, trivial thing. Its analysis brings out that it is a very strange thing.',
    'Surplus value is extracted through the extension of the working day.',
    'Marx analyzes how commodities conceal human social relations behind price exchange.',
    'https://www.gutenberg.org/ebooks/6130',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Surplus Value', 'Commodity Fetishism', 'Macroeconomics'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000076',
    'The General Theory of Employment, Interest and Money',
    'John Maynard Keynes',
    'Economics & Behaviour',
    'Revolutionary work on aggregate demand, liquidity preference, and economic downturns.',
    'Why can market economies suffer prolonged underemployment without active intervention?',
    'The market can stay irrational longer than you can stay solvent.',
    'Aggregate demand determines economic output and employment levels.',
    'Keynes demonstrated how liquidity preference and falling investment cause recessions.',
    'https://archive.org/details/generaltheoryofe00keyn',
    'Internet Archive',
    'archive',
    'advanced',
    'book',
    ARRAY['Keynesian Economics', 'Aggregate Demand', 'Macroeconomics'],
    '#17191D',
    false,
    false,
    true
),

-- ============================================================================
-- 11. ✍️ LITERATURE (6 works)
-- ============================================================================
(
    '30000000-0000-0000-0000-000000000077',
    'Poetics',
    'Aristotle',
    'Literature',
    'Foundational treatise on dramatic theory, tragedy, catharsis, and narrative structure.',
    'Why does tragedy produce a purifying release of pity and fear in the audience?',
    'Tragedy is an imitation of an action that is serious, complete, and of a certain magnitude.',
    'Through pity and fear, tragedy accomplishes its catharsis of emotions.',
    'Tragedy is an imitation of an action that is serious, complete, and of a certain magnitude; in language embellished with each kind of artistic ornament; through pity and fear accomplishing its catharsis of such emotions.',
    'https://www.gutenberg.org/ebooks/1974',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Dramatic Theory', 'Catharsis', 'Tragedy'],
    '#17191D',
    true,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000078',
    'Biographia Literaria',
    'Samuel Taylor Coleridge',
    'Literature',
    'Literary theory introducing the willing suspension of disbelief and primary vs secondary imagination.',
    'How does poetic imagination transform sensory memory into living art?',
    'That willing suspension of disbelief for the moment, which constitutes poetic faith.',
    'Imagination dissolves, diffuses, dissipates, in order to recreate.',
    'Coleridge defined poetic faith as the willing suspension of disbelief.',
    'https://www.gutenberg.org/ebooks/6081',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Literary Theory', 'Imagination', 'Suspension of Disbelief'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000079',
    'The Idea of a University',
    'John Henry Newman',
    'Literature',
    'Classic defense of liberal education, critical judgment, and intellectual breadth.',
    'Why is liberal education valuable for its own sake rather than narrow vocational utility?',
    'Knowledge is capable of being its own end.',
    'A university is a place of teaching universal knowledge.',
    'Newman argues that cultivating intellectual discernment is the primary aim of higher learning.',
    'https://www.gutenberg.org/ebooks/24526',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Liberal Education', 'Intellectual Growth', 'University'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000080',
    'A Defence of Poetry',
    'Percy Bysshe Shelley',
    'Literature',
    'Passionate essay arguing that poets and creative thinkers shape moral consciousness.',
    'Why are poets the unacknowledged legislators of the world?',
    'Poets are the unacknowledged legislators of the world.',
    'Poetry lifts the veil from the hidden beauty of the world.',
    'Shelley argues that poetic imagination expands human empathy and ethical life.',
    'https://www.gutenberg.org/ebooks/5429',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'essay',
    ARRAY['Poetics', 'Empathy', 'Literary Philosophy'],
    '#17191D',
    false,
    true,
    true
),
(
    '30000000-0000-0000-0000-000000000081',
    'Shakespearean Tragedy',
    'A.C. Bradley',
    'Literature',
    'Landmark literary analysis of Hamlet, Othello, King Lear, and Macbeth.',
    'How do tragic flaws in noble characters bring about unavoidable catastrophe?',
    'A Shakespearean tragedy is pre-eminently a story of one person: the tragic hero.',
    'The tragic flaw converts great virtues into instruments of destruction.',
    'Bradley''s character studies remain a cornerstone of dramatic literary analysis.',
    'https://www.gutenberg.org/ebooks/16000',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Shakespeare', 'Tragic Hero', 'Dramatic Analysis'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000082',
    'Literary Essays',
    'Ezra Pound',
    'Literature',
    'Incisive essays on poetic cadence, imagism, translation, and literary precision.',
    'Why should literature be news that stays news?',
    'Literature is news that stays news.',
    'Great literature is simply language charged with meaning to the utmost possible degree.',
    'Pound urges writers to make it new through precision and elimination of superfluous fluff.',
    'https://archive.org/details/literaryessaysof00poun',
    'Internet Archive',
    'archive',
    'intermediate',
    'essay',
    ARRAY['Imagism', 'Poetic Precision', 'Literary Criticism'],
    '#17191D',
    false,
    false,
    true
),

-- ============================================================================
-- 12. 💻 TECHNOLOGY (6 works)
-- ============================================================================
(
    '30000000-0000-0000-0000-000000000083',
    'Computing Machinery and Intelligence',
    'Alan Turing',
    'Technology',
    'Foundational 1950 paper proposing the Imitation Game (Turing Test) and machine intelligence.',
    'Can machines think, and how do we measure artificial intelligence?',
    'I propose to consider the question: Can machines think?',
    'If a machine can converse indistinguishably from a human, it exhibits intelligence.',
    'Turing considers whether computers can imitate human thought, outlining early AI concepts.',
    'https://archive.org/details/turing-1950-mind',
    'Internet Archive',
    'archive',
    'intermediate',
    'paper',
    ARRAY['Artificial Intelligence', 'Turing Test', 'Computer Science'],
    '#17191D',
    true,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000084',
    'A Mathematical Theory of Communication',
    'Claude E. Shannon',
    'Technology',
    'Foundational paper establishing Information Theory, binary bits, and entropy in digital communications.',
    'How do we measure information mathematically across noisy communication channels?',
    'The fundamental problem of communication is that of reproducing at one point a message selected at another point.',
    'Information entropy measures uncertainty in digital signal transmission.',
    'Shannon defined the mathematical bit and laid the foundation for modern digital networks.',
    'https://archive.org/details/shannon1948',
    'Internet Archive',
    'archive',
    'advanced',
    'paper',
    ARRAY['Information Theory', 'Binary Bits', 'Digital Communication'],
    '#17191D',
    false,
    false,
    true
);
