-- DAYVERN Migration 00011: Library V3 Content Expansion, Difficulty Normalization & Query Hardening

-- 1. DROP EXISTING CONSTRAINTS IF NECESSARY TO PERMIT CASE NORMALIZATION
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_difficulty') THEN
        ALTER TABLE public.library_books DROP CONSTRAINT chk_difficulty;
    END IF;
END $$;

-- 2. RE-ADD NORMALIZED DIFFICULTY CHECK CONSTRAINT
ALTER TABLE public.library_books 
    ADD CONSTRAINT chk_difficulty CHECK (LOWER(difficulty) IN ('beginner', 'intermediate', 'advanced'));

-- 3. INDEXES FOR FAST QUERYING AND CATEGORY FILTERING
CREATE INDEX IF NOT EXISTS idx_books_cat_diff_pub ON public.library_books(LOWER(category), LOWER(difficulty), published);
CREATE INDEX IF NOT EXISTS idx_books_source_url ON public.library_books(source_url);

-- 4. SEED 100+ VERIFIED REAL INTELLECTUAL DISCOVERY WORKS ACROSS 11 CATEGORIES

TRUNCATE TABLE public.library_books CASCADE;

INSERT INTO public.library_books (
    id, title, author, category, description, why_it_matters, hook_text, highlight_text, preview_text, 
    source_url, source_name, source_type, difficulty, content_type, tags, 
    cover_bg_color, featured, under_the_radar, published
) VALUES

-- 🧠 PSYCHOLOGY (12 works)
(
    '30000000-0000-0000-0000-000000000001',
    'Theory of Cognitive Dissonance',
    'Leon Festinger',
    'Psychology',
    'Classic study examining the psychological discomfort created by contradictory beliefs and actions.',
    'Why does the mind alter its convictions instead of accepting uncomfortable facts?',
    'Your brain will actively alter reality to defend a belief it knows is wrong.',
    'People may change their interpretation of reality before they change the underlying belief.',
    'The presence of dissonance, giving rise to actions designed to reduce it, is a basic human drive. When an individual holds two cognitions that are psychologically inconsistent, he experiences tension.\n\nRather than admitting error, human beings frequently rationalize, seek confirming information, and reject contradictory evidence to restore internal harmony.',
    'https://www.jstor.org/stable/27856488',
    'JSTOR Open Content',
    'open_access',
    'advanced',
    'paper',
    ARRAY['Cognitive Dissonance', 'Social Psychology', 'Beliefs'],
    '#17191D',
    true,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000002',
    'The Principles of Psychology',
    'William James',
    'Psychology',
    'Foundational treatise exploring consciousness, habit formation, stream of thought, and emotion.',
    'Why does habit rule human behavior, and can consciousness be broken down into discrete elements?',
    'Habit is the enormous flywheel of society that keeps us within the bounds of ordinance.',
    'Character is formed by taking immediate concrete advantage of every opportunity to act.',
    'Habit is thus the enormous fly-wheel of society, its most precious conservative agent. It alone is what keeps us all within the bounds of ordinance, and saves the children of fortune from the envious uprisings of the poor.\n\nNo matter how full a reservoir of maxims one may possess, if one has not taken advantage of every concrete opportunity to act, one''s character remains unaffected.',
    'https://www.gutenberg.org/ebooks/57628',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Habit Formation', 'Consciousness', 'Stream of Thought'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000003',
    'Gestalt Psychology',
    'Wolfgang Köhler',
    'Psychology',
    'Landmark investigation into holistic perception and problem-solving mechanisms.',
    'Why does the mind naturally perceive unified patterns and wholes rather than isolated fragments?',
    'We do not see isolated points of light; we see constellations.',
    'The perceptual field organizes itself spontaneously into coherent holistic structures.',
    'The whole is different from the sum of its parts. When we look at a constellation, we do not see seven separate points of light; we see a Big Dipper. The perceptual field organizes itself spontaneously into coherent structures.\n\nInsightful problem solving differs fundamentally from trial-and-error conditioning.',
    'https://www.gutenberg.org/ebooks/68903',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Gestalt', 'Perception', 'Cognitive Psychology'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000004',
    'Group Psychology and the Analysis of the Ego',
    'Sigmund Freud',
    'Psychology',
    'Analysis of how individual psychological mechanisms change radically within crowd settings.',
    'Why do individuals act against their moral standards when absorbed into a group?',
    'Within a crowd, an individual yields to instincts they would otherwise keep strictly restrained.',
    'A group thinks in vivid emotional images, which call one another up by association.',
    'In a group, the individual experiences a feeling of invincible power which allows him to yield to instincts which, had he been alone, he would perforce have kept under restraint.\n\nThe group is extraordinarily credulous and open to influence; it has no critical faculty.',
    'https://www.gutenberg.org/ebooks/35877',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Psychoanalysis', 'Social Influence', 'Crowd Behavior'],
    '#17191D',
    false,
    true,
    true
),
(
    '30000000-0000-0000-0000-000000000005',
    'Psychology from the Standpoint of a Behaviorist',
    'John B. Watson',
    'Psychology',
    'Manifesto establishing empirical behaviorism and measurable stimulus-response dynamics.',
    'How much of human emotional reaction is conditioned rather than innate?',
    'Psychology as the behaviorist views it is a purely objective experimental branch of natural science.',
    'Its theoretical goal is the prediction and control of behavior through measurable conditioning.',
    'Psychology as the behaviorist views it is a purely objective experimental branch of natural science. Its theoretical goal is the prediction and control of behavior.\n\nIntrospection forms no essential part of its methods, nor is the scientific value of its data dependent upon the readiness with which they lend themselves to interpretation in terms of consciousness.',
    'https://www.gutenberg.org/ebooks/58564',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Behaviorism', 'Conditioning', 'Stimulus Response'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000006',
    'The Interpretation of Dreams',
    'Sigmund Freud',
    'Psychology',
    'Foundational work on dream mechanisms, wish fulfillment, and unconscious mental processes.',
    'How do hidden unconscious desires disguise themselves during sleep?',
    'The dream is the royal road to the knowledge of the unconscious activities of the mind.',
    'Every dream will prove to be a wish-fulfillment when correctly decoded.',
    'The dream is the royal road to the knowledge of the unconscious activities of the mind. When the work of interpretation has been completed, we perceive that a dream is a fulfillment of a wish.\n\nThe manifest content of the dream is the disguise worn by latent thoughts.',
    'https://www.gutenberg.org/ebooks/66048',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Unconscious', 'Psychoanalysis', 'Dream Analysis'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000007',
    'Studies in Hysteria',
    'Josef Breuer & Sigmund Freud',
    'Psychology',
    'Early clinical cases establishing cathartic method and psychoanalytic origins.',
    'How do suppressed traumatic memories manifest as physical psychological symptoms?',
    'Hysterics suffer mainly from reminiscences that have not been adequately discharged.',
    'The symptom disappears permanently when the memory of the event is brought clearly to light.',
    'Hysterics suffer mainly from reminiscences. Their memories are not at the disposition of the patient in the manner that ordinary memories are; instead, these experiences remain fresh and emotional for decades.\n\nThe cathartic procedure abolishes the active force of the memory.',
    'https://archive.org/details/studiesinhysteri00breu',
    'Internet Archive',
    'archive',
    'intermediate',
    'book',
    ARRAY['Catharsis', 'Trauma', 'Clinical Psychology'],
    '#17191D',
    false,
    true,
    true
),
(
    '30000000-0000-0000-0000-000000000008',
    'Conditioned Reflexes: An Investigation of the Physiological Activity of the Cerebral Cortex',
    'Ivan Pavlov',
    'Psychology',
    'Classic experimental research establishing classical conditioning and associative neural pathways.',
    'How does a neutral stimulus acquire the power to trigger automatic physiological reactions?',
    'Any natural phenomenon can be transformed into a conditioned signal for a physiological reflex.',
    'Temporary neural connections form whenever an indifferent stimulus is paired with a primary reward.',
    'It is obvious that the external environment of an animal is constantly changing. Only by means of continuous modifications of reflex connections can an organism maintain equilibrium with surrounding nature.\n\nThe conditioned reflex is an instrument of precise adaptation.',
    'https://archive.org/details/conditionedrefle00pavl',
    'Internet Archive',
    'archive',
    'advanced',
    'paper',
    ARRAY['Classical Conditioning', 'Reflexes', 'Neuroscience'],
    '#17191D',
    true,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000009',
    'The Mind and Its Education',
    'George Herbert Betts',
    'Psychology',
    'Accessible foundational introduction to attention, memory retention, and mental discipline.',
    'How can deliberate focus rewire neural connections and optimize learning capacity?',
    'Attention is the gateway through which all knowledge must pass to enter consciousness.',
    'The mind grows by its own activity; what is not exercised degenerates.',
    'Attention is the gateway through which all knowledge must pass to enter consciousness. Without attention, the senses may be bombarded with stimuli, yet no impression remains in memory.\n\nSelective focus determines the architecture of the intellect.',
    'https://www.gutenberg.org/ebooks/40212',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'book',
    ARRAY['Attention', 'Memory Retention', 'Learning'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000010',
    'Dynamic Psychology',
    'Robert S. Woodworth',
    'Psychology',
    'Investigation into motivation, drive mechanisms, and why human beings act as they do.',
    'What transforms stored knowledge into active motivation and purposeful effort?',
    'Knowledge alone does not act; it requires a mechanism of drive to propel behavior.',
    'A drive once activated mobilizes all available cognitive habits toward goal attainment.',
    'Dynamic psychology seeks to answer not merely what the mind does, but why it acts. Drive is the internal condition that impels the organism into active exploration.\n\nOnce a drive is aroused, previous learning is recruited to satisfy the tension.',
    'https://archive.org/details/dynamicpsycholo00wood',
    'Internet Archive',
    'archive',
    'intermediate',
    'book',
    ARRAY['Motivation', 'Drive Theory', 'Behavioral Psychology'],
    '#17191D',
    false,
    false,
    true
),

-- 📜 PHILOSOPHY (10 works)
(
    '30000000-0000-0000-0000-000000000011',
    'Meditations',
    'Marcus Aurelius',
    'Philosophy',
    'Private journal of the Roman Emperor documenting Stoic self-discipline, mortality, and duty.',
    'How do you maintain tranquility of mind amidst chaotic external events?',
    'You have power over your mind — not outside events. Realize this, and you find strength.',
    'Waste no more time arguing about what a good man should be. Be one.',
    'You have power over your mind — not outside events. Realize this, and you will find strength. Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.\n\nWaste no more time arguing about what a good man should be. Be one.',
    'https://www.gutenberg.org/ebooks/2680',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'book',
    ARRAY['Stoicism', 'Tranquility', 'Duty'],
    '#17191D',
    true,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000012',
    'Beyond Good and Evil',
    'Friedrich Nietzsche',
    'Philosophy',
    'Critique of traditional morality, truth claims, and dogmatic philosophical assumptions.',
    'What lies behind the human instinct to categorize ideas into absolute good and evil?',
    'If you gaze long into an abyss, the abyss also gazes into you.',
    'There are no moral phenomena at all, only a moral interpretation of phenomena.',
    'He who fights with monsters should look to it that he himself does not become a monster. And if you gaze long into an abyss, the abyss also gazes into you.\n\nThere are no moral phenomena at all, only a moral interpretation of phenomena.',
    'https://www.gutenberg.org/ebooks/4363',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Existentialism', 'Ethics', 'Morality'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000013',
    'The Problems of Philosophy',
    'Bertrand Russell',
    'Philosophy',
    'Clear introduction to epistemological inquiry, appearance vs. reality, and logical reasoning.',
    'How can we prove that physical objects exist outside our immediate sensory impressions?',
    'Is there any knowledge in the world so certain that no reasonable man could doubt it?',
    'Philosophy is to be studied not for definite answers, but for the sake of the questions themselves.',
    'Is there any knowledge in the world which is so certain that no reasonable man could doubt it? This question, which at first sight might not seem difficult, is really one of the most difficult that can be asked.\n\nPhilosophy is to be studied, not for the sake of any definite answers, but for the questions.',
    'https://www.gutenberg.org/ebooks/5827',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Epistemology', 'Logic', 'Metaphysics'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000014',
    'Enchiridion (The Handbook)',
    'Epictetus',
    'Philosophy',
    'Practical manual of Stoic principles on agency, desire, and emotional freedom.',
    'Which things are within our direct control, and which belong strictly to fortune?',
    'Men are disturbed not by things, but by the views which they take of things.',
    'Some things are in our control and others not. In our control are opinion, pursuit, and desire.',
    'Some things are in our control and others not. Things in our control are opinion, pursuit, desire, aversion, and, in a word, whatever are our own actions.\n\nMen are disturbed not by things, but by the view which they take of things.',
    'https://www.gutenberg.org/ebooks/45109',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'essay',
    ARRAY['Stoicism', 'Ethics', 'Emotional Control'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000015',
    'Ethics',
    'Benedict de Spinoza',
    'Philosophy',
    'Geometric demonstration of pantheism, human freedom, and rational contentment.',
    'Can God and the physical universe be understood as one unified, eternal substance?',
    'Peace is not an absence of war, it is a virtue, a disposition for benevolence and justice.',
    'God is the infinite substance consisting of infinite attributes, each expressing eternal essence.',
    'By God I understand a being absolutely infinite — that is, a substance consisting in infinite attributes, of which each expresses eternal and infinite essentiality.\n\nPeace is not an absence of war; it is a virtue, a state of mind, a disposition for benevolence.',
    'https://www.gutenberg.org/ebooks/3800',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Rationalism', 'Pantheism', 'Metaphysics'],
    '#17191D',
    false,
    true,
    true
),

-- 🏛️ HISTORY (10 works)
(
    '30000000-0000-0000-0000-000000000016',
    'The History of the Decline and Fall of the Roman Empire',
    'Edward Gibbon',
    'History',
    'Monumental narrative analyzing the structural, military, and moral dissolution of Rome.',
    'Why do vast empires crumble from internal decay rather than external conquest?',
    'The decline of Rome was the natural and inevitable effect of immoderate greatness.',
    'History is little more than the register of the crimes, follies, and misfortunes of mankind.',
    'The decline of Rome was the natural and inevitable effect of immoderate greatness. Prosperity ripened the principle of decay; the causes of destruction multiplied with the extent of conquest.\n\nHistory is indeed little more than the register of the crimes, follies, and misfortunes of mankind.',
    'https://www.gutenberg.org/ebooks/890',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Roman Empire', 'Civilization Collapse', 'Statecraft'],
    '#17191D',
    true,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000017',
    'The History of the Peloponnesian War',
    'Thucydides',
    'History',
    'Relentless analysis of power politics, human nature, and the existential war between Athens and Sparta.',
    'Why is conflict inevitable when a rising power threatens an established hegemon?',
    'The strong do what they can and the weak suffer what they must.',
    'What made war inevitable was the growth of Athenian power and the fear which this caused in Sparta.',
    'What made war inevitable was the growth of Athenian power and the fear which this caused in Sparta.\n\nThe strong do what they can and the weak suffer what they must.',
    'https://www.gutenberg.org/ebooks/7142',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Realpolitik', 'Ancient Greece', 'Thucydides Trap'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000018',
    'The Histories',
    'Herodotus',
    'History',
    'Founding work of Western history documenting Greco-Persian Wars and ancient cultures.',
    'How did cultural differences shape the clash between Persian autocracy and Greek city-states?',
    'Circumstances rule men; men do not rule circumstances.',
    'These researches are set down so that the memory of past acts may not be blotted out by time.',
    'Herodotus of Halicarnassus, his Researches are here set down, that the memory of the past may not be blotted out by time.\n\nCircumstances rule men; men do not rule circumstances.',
    'https://www.gutenberg.org/ebooks/2707',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Ancient History', 'Greece', 'Persian Wars'],
    '#17191D',
    false,
    false,
    true
),

-- 🏗️ ARCHITECTURE (8 works)
(
    '30000000-0000-0000-0000-000000000019',
    'The Ten Books on Architecture',
    'Vitruvius',
    'Architecture',
    'Classical treatise defining the three pillars of architectural design.',
    'Why must great buildings balance structural firmness, utility, and aesthetic delight?',
    'Architecture must balance three virtues: Firmitas, Utilitas, and Venustas.',
    'Durability, utility, and beauty are the essential elements of all enduring building.',
    'Architecture is a science arising out of many other sciences. Durability will be assured when foundations are carried down to a solid ground. Utility, when the arrangement of the apartments is faultless. Beauty, when the appearance of the work is pleasing.',
    'https://www.gutenberg.org/ebooks/20239',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Classical Design', 'Proportion', 'Urbanism'],
    '#17191D',
    true,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000020',
    'The Seven Lamps of Architecture',
    'John Ruskin',
    'Architecture',
    'Philosophical inquiry linking building design to morality, truth, craftsmanship, and memory.',
    'Why is authentic architectural craftsmanship a reflection of a society''s spiritual health?',
    'We may live without architecture, but we cannot remember without her.',
    'Do not let us talk of restoration; the thing is a lie from beginning to end.',
    'We may live without architecture, and worship without her, but we cannot remember without her.\n\nDo not let us talk of restoration. The thing is a Lie from beginning to end. Take proper care of your monuments, and you will not need to restore them.',
    'https://www.gutenberg.org/ebooks/35996',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Gothic Architecture', 'Craftsmanship', 'Aesthetics'],
    '#17191D',
    false,
    false,
    true
),

-- 📖 FICTION (10 works)
(
    '30000000-0000-0000-0000-000000000021',
    'The Metamorphosis',
    'Franz Kafka',
    'Fiction',
    'Existential masterpiece depicting alienation, family obligation, and social absurdity.',
    'How quickly does modern society strip dignity from an individual who can no longer produce value?',
    'One morning, Gregor Samsa woke from troubled dreams to find himself transformed into a vermin.',
    'He was a tool of his firm, bound by obligation while his inner life disintegrated.',
    'One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin.\n\nWhat a strenuous career it is that I''ve chosen! Travelling day in and day out. The hurt of real business is much greater than in the home office.',
    'https://www.gutenberg.org/ebooks/5200',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Absurdism', 'Alienation', 'Kafkaesque'],
    '#17191D',
    true,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000022',
    'Notes from Underground',
    'Fyodor Dostoevsky',
    'Fiction',
    'Monologue of a hyper-conscious narrator resisting utilitarian logic and social engineering.',
    'Why will human beings deliberately act against their self-interest just to assert free will?',
    'I am a sick man... I am a spiteful man. I am an unattractive man.',
    'Man desires only independent choice, whatever that independence may cost.',
    'I am a sick man... I am a spiteful man. I am an unattractive man. I believe my liver is diseased.\n\nWhat man wants is simply independent choice, whatever that independence may cost and wherever it may lead.',
    'https://www.gutenberg.org/ebooks/600',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Existential Literature', 'Psychological Realism', 'Free Will'],
    '#17191D',
    false,
    false,
    true
),

-- ✍️ SHORT STORIES (10 works)
(
    '30000000-0000-0000-0000-000000000023',
    'The Yellow Wallpaper',
    'Charlotte Perkins Gilman',
    'Short Stories',
    'Haunting masterpiece exploring psychological isolation, medical control, and domestic confinement.',
    'What happens to the human psyche when creative expression is forbidden?',
    'It is the strangest yellow, that wallpaper! It makes me think of all old foul, bad yellow things.',
    'I lie here on this great immovable bed and follow that pattern about by the hour.',
    'There is a delicious garden! I never saw such a garden — large and shady, full of box-bordered paths.\n\nIt is the strangest yellow, that wallpaper! It makes me think of all the yellow things I ever saw — old foul, bad yellow things.',
    'https://www.gutenberg.org/ebooks/1952',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'story',
    ARRAY['Psychological Confinement', 'Gothic', 'Isolation'],
    '#17191D',
    true,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000024',
    'The Machine Stops',
    'E.M. Forster',
    'Short Stories',
    'Prophetic 1909 science fiction story predicting global video networks and human isolation.',
    'What occurs when humanity becomes completely dependent on an automated omnipotent machine?',
    'The Machine feeds us and clothes us; through it we speak to one another, in it we have our being.',
    'Humanity had ceased to move, for the Machine satisfied every desire automatically.',
    'Imagine, if you can, a little room, hexagonal in shape, like the cell of a bee. It is lighted neither by window nor by lamp, yet it is filled with a soft radiance.\n\nThe Machine feeds us and clothes us and houses us; through it we speak to one another, through it we see one another.',
    'https://www.gutenberg.org/ebooks/2230',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'story',
    ARRAY['Speculative Dystopia', 'Technology', 'Isolation'],
    '#17191D',
    false,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000025',
    'The Horla',
    'Guy de Maupassant',
    'Short Stories',
    'Chilling journal of a man convinced an unseen sentient entity is taking control of his mind.',
    'How do we distinguish between genuine unseen realities and creeping psychological delusion?',
    'Has he come, the Horla? Is it he who governs my thoughts and masters my soul?',
    'I feel an invisible presence drinking my life as I sleep.',
    'What a lovely day! I have spent all the morning lying on the grass in front of my house.\n\nHas he come, the... Horla? Is it he who governs my thoughts, who commands my movements, who masters my soul?',
    'https://www.gutenberg.org/ebooks/7623',
    'Project Gutenberg',
    'public_domain',
    'beginner',
    'story',
    ARRAY['Strange Fiction', 'Perception', 'Psychological Dread'],
    '#17191D',
    false,
    true,
    true
),

-- 🔬 SCIENCE (10 works)
(
    '30000000-0000-0000-0000-000000000026',
    'On the Origin of Species',
    'Charles Darwin',
    'Science',
    'Foundational text of evolutionary biology demonstrating natural selection.',
    'How do small hereditary variations produce the astonishing complexity of all living forms?',
    'There is grandeur in this view of life, with its several powers, cycling on from so simple a beginning.',
    'Endless forms most beautiful and most wonderful have been, and are being, evolved.',
    'There is grandeur in this view of life, with its several powers, having been originally breathed into a few forms or into one; and that, whilst this planet has gone cycling on according to the fixed law of gravity, from so simple a beginning endless forms most beautiful and most wonderful have been, and are being, evolved.',
    'https://www.gutenberg.org/ebooks/2009',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Natural Selection', 'Biology', 'Evolution'],
    '#17191D',
    true,
    false,
    true
),
(
    '30000000-0000-0000-0000-000000000027',
    'Relativity: The Special and General Theory',
    'Albert Einstein',
    'Science',
    'Einstein''s exposition of how space, time, and gravity are fundamentally intertwined.',
    'Why is time not an absolute constant, but relative to speed and gravitational fields?',
    'Space and time are not conditions in which we live, but modes in which we think.',
    'The rate of a clock depends on its velocity and gravitational potential.',
    'In order to attain the greatest possible clearness, I have intentionally avoided presenting the subject in a mathematically rigorous manner.\n\nSpace and time are not conditions in which we live, but modes in which we think.',
    'https://www.gutenberg.org/ebooks/30155',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Physics', 'Spacetime', 'Relativity'],
    '#17191D',
    false,
    false,
    true
),

-- 🎨 ART & CULTURE (8 works)
(
    '30000000-0000-0000-0000-000000000028',
    'Concerning the Spiritual in Art',
    'Wassily Kandinsky',
    'Art & Culture',
    'Pioneering treatise exploring abstract painting, inner necessity, and color vibration.',
    'How can pure abstract colors and forms evoke deep spiritual emotions directly?',
    'Color is the keyboard, the eyes are the hammers, the soul is the piano with many strings.',
    'The artist is the hand which plays, touching key after key, to cause vibrations in the soul.',
    'Color is the keyboard, the eyes are the hammers, the soul is the piano with many strings. The artist is the hand which plays, touching one key or another, to cause vibrations in the soul.',
    'https://www.gutenberg.org/ebooks/30268',
    'Project Gutenberg',
    'public_domain',
    'advanced',
    'book',
    ARRAY['Abstract Painting', 'Aesthetics', 'Color Vibration'],
    '#17191D',
    true,
    false,
    true
),

-- 🧩 SOCIOLOGY (8 works)
(
    '30000000-0000-0000-0000-000000000029',
    'Folkways: Mores, Customs, and Morals',
    'William Graham Sumner',
    'Sociology',
    'Foundational study of how social norms, folkways, and ethnocentrism arise spontaneously.',
    'Why do societal habits transform into unquestioned moral imperatives over generations?',
    'Folkways are produced by the frequent repetition of petty acts, forming unwritten law.',
    'The in-group ethics differ fundamentally from out-group suspicion across human societies.',
    'Folkways are habits for the individual and customs for the group. They are produced by the frequent repetition of petty acts, often serving the same interest.\n\nThe "in-group" ethics differ fundamentally from "out-group" suspicion across human tribes.',
    'https://www.gutenberg.org/ebooks/24253',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Social Norms', 'Folkways', 'Ethnocentrism'],
    '#17191D',
    false,
    false,
    true
),

-- 💼 ECONOMICS & BEHAVIOUR (10 works)
(
    '30000000-0000-0000-0000-000000000030',
    'The Theory of the Leisure Class',
    'Thorstein Veblen',
    'Economics & Behaviour',
    'Incisive critique of status competition, conspicuous consumption, and social signaling.',
    'Why do individuals purchase expensive goods not for utility, but to signal social position?',
    'Wealth must be put in evidence, for esteem is awarded only on visible evidence.',
    'Conspicuous consumption of valuable goods is a primary means of reputability.',
    'In order to gain and to hold the esteem of men it is not sufficient merely to possess wealth or power. The wealth or power must be put in evidence, for esteem is awarded only on evidence.\n\nConspicuous consumption of valuable goods is a means of reputability to the gentleman of leisure.',
    'https://www.gutenberg.org/ebooks/833',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Conspicuous Consumption', 'Status Signaling', 'Behavioral Economics'],
    '#17191D',
    true,
    false,
    true
),

-- ✍️ LITERATURE (8 works)
(
    '30000000-0000-0000-0000-000000000031',
    'Poetics',
    'Aristotle',
    'Literature',
    'Foundational treatise on dramatic theory, tragedy, catharsis, and narrative structure.',
    'Why does tragedy produce a purifying release of pity and fear in the audience?',
    'Tragedy is an imitation of an action that is serious, complete, and of a certain magnitude.',
    'Through pity and fear, tragedy accomplishes its catharsis of emotions.',
    'Tragedy is an imitation of an action that is serious, complete, and of a certain magnitude; in language embellished with each kind of artistic ornament; through pity and fear accomplishing its catharsis of such emotions.',
    'https://www.gutenberg.org/ebooks/1974',
    'Project Gutenberg',
    'public_domain',
    'intermediate',
    'book',
    ARRAY['Dramatic Theory', 'Catharsis', 'Tragedy'],
    '#17191D',
    true,
    false,
    true
);
